DavidoTek/ProtonUp-Qt

- pupgui2/constants.py
- pupgui2/pupgui2.py
- pupgui2/pupgui2ctbatchupdatedialog.py
- pupgui2/pupgui2ctinfodialog.py
- pupgui2/pupgui2gamelistdialog.py
- pupgui2/util.py
- share/pupgui2/ui/pupgui2_gamelistdialog.ui
- share/pupgui2/ui/pupgui2_mainwindow.ui
- Shows a list of installed games
- Compatibility tool can be set/removed/changed
**ToDo:**
- Show non-GE Proton versions
> Add gamelist dialog (Steam)

- pupgui2/constants.py
- pupgui2/pupgui2customiddialog.py
- pupgui2/resources/ctmods/ctmod_00protonge.py
- pupgui2/resources/ctmods/ctmod_00winege.py
- pupgui2/resources/ctmods/ctmod_lutriswine.py
> Add support for Bottles

- i18n/pupgui2_nl.ts
> Updated Dutch translation

- pupgui2/resources/ctmods/ctmod_z2dxvknightly.py
This PR changes dxvk nightly name from `dxvk-master-<hash>` to `dxvk-git-<short hash>` because:
1. I don't want to type `dxvk-master-1c35fbb33c424f27253f7e5412358da40fad51b5` in Lutris, typing just `dxvk-git-1c35fbb` is much easier :P
2. You can tell the branch they're compiled from by the commit hash, so the "master" part is not needed. Instead we use "git" to define this is a git version.
> misc: change dxvk nightly installed name to something shorter

- pupgui2/resources/ctmods/ctmod_northstarproton.py
Adds [NorthstarProton](https://github.com/cyrv6737/NorthstarProton) compatibility tool by @cyrv6737. Advanced mode needs to be enabled to install it.
Closes https://github.com/DavidoTek/ProtonUp-Qt/issues/115.
> Add NorthstarProton compatibility tool

- pupgui2/resources/ctmods/ctmod_00protonge.py
- pupgui2/resources/ctmods/ctmod_00winege.py
- pupgui2/resources/ctmods/ctmod_boxtron.py
- pupgui2/resources/ctmods/ctmod_d8vk.py
- pupgui2/resources/ctmods/ctmod_kron4ekvanilla.py
- pupgui2/resources/ctmods/ctmod_lutriswine.py
- pupgui2/resources/ctmods/ctmod_luxtorpeda.py
- pupgui2/resources/ctmods/ctmod_northstarproton.py
- pupgui2/resources/ctmods/ctmod_protontkg.py
- pupgui2/resources/ctmods/ctmod_roberta.py
- pupgui2/resources/ctmods/ctmod_steamtinkerlaunch.py
- pupgui2/resources/ctmods/ctmod_vkd3dlutris.py
- pupgui2/resources/ctmods/ctmod_vkd3dproton.py
- pupgui2/resources/ctmods/ctmod_z0dxvk.py
- pupgui2/resources/ctmods/ctmod_z1dxvkasync.py
- pupgui2/resources/ctmods/ctmod_z2dxvknightly.py
- pupgui2/util.py
- Adds a warning that is printed to console when the GitHub API rate limit is exceeded
- Fixes crashes that occur when the rate limit is exceeded
See https://github.com/DavidoTek/ProtonUp-Qt/issues/161
> Add GitHub API rate limit warning

- pupgui2/pupgui2.py
- pupgui2/steamutil.py
Close https://github.com/DavidoTek/ProtonUp-Qt/issues/60
A few changes for improving the start time of ProtonUp-Qt.
Mainly some optimizations and avoidance of loops.
> Optimize start time

- pupgui2/ctloader.py
- pupgui2/util.py
> feat: show message box for CTs failed to load

- pupgui2/steamutil.py
See https://github.com/DavidoTek/ProtonUp-Qt/issues/202
> Always print exception in try-catch and fix default type of compat_tools

- pupgui2/pupgui2gamelistdialog.py
This PR enables caching when opening the Steam Games List to give a major speed boost, reducing the time it takes to open from a couple of seconds to a fraction of a second. 
In the games list, the `update_game_list_steam` method makes two calls: One to `get_steam_game_list`, and then another to `get_steam_ctool_list`. These both internally make calls to `get_steam_app_list`. This has been massively sped up since #171 (seriously, 2.7.7 is painfully slow in comparison, that fix rocks!), but it can still take around 2 seconds. Making the call twice does add a noticeable delay for opening the Steam Games List.
The `get_steam_app_list` method has an optional `cached` parameter, which returns the cached games list. From what I can understand this cache is generated based on the last call to …
> Games List: Use cached list for Steam

- pupgui2/pupgui2ctinfodialog.py
Same as #211 but for the ctinfo dialog. I'm dumb and forgot the info dialog would benefit from the same change :face_exhaling:
> CtInfo: Use cached Steam game list

- pupgui2/resources/ui/pupgui2_ctinfodialog.ui
- pupgui2/resources/ui/pupgui2_gamelistdialog.ui
tbd
See https://github.com/DavidoTek/ProtonUp-Qt/issues/206#issuecomment-1480347351
> Rework Tab Order

- README.md
Close https://github.com/DavidoTek/ProtonUp-Qt/issues/65
Created a project for ProtonUp-Qt on Weblate: https://hosted.weblate.org/projects/protonup-qt/
> README: Add Weblate Project URL

- i18n/release_i18n.sh
- i18n/update_i18n.sh
Usage:
1. `bash i18n/update_18n.sh`
2. `bash i18n/release_i18n.sh`
> Add i18n Scripts

- pupgui2/resources/ctmods/ctmod_roberta.py
This PR is the same as #311 but for the Roberta ctmod. Roberta is also a sister project of Luxtorpeda, and the changes here make Boxtron and Roberta identical right down to the number of lines save for differences in URLs, dependencies, and the name/description strings :-)
> Roberta: Use Subclass of Luxtorpeda

- pupgui2/pupgui2.py
- pupgui2/pupgui2shortcutdialog.py
Was working on another PR and noticed some unused imports. Went through all files to see if I could find any others, think I got them all :-)
> misc: remove some unused imports

- AppImageBuilder.yml
- pupgui2/constants.py
- pupgui2/pupgui2exceptionhandler.py
- setup.cfg
Fixed compatibility with Python 3.8 (for the AppImage)....
> Bump version to 2.9.1 (Fix Python 3.8 compatibility again)

- setup.cfg
- `setup.cfg`: `python_requires = >=3.6` -> `python_requires = >=3.10`
> Bump Python version requirement to 3.10

- pupgui2/resources/ctmods/ctmod_steamplaynone.py
**Note**: This PR depends on #489.
This PR refactors the Steam-Play-None download logic to use `networkutil#download_file.` Following discussion in #486, I will try to make time to review and port more ctmods over to using this util function :-)
The actual download logic is longer because of formatting, but overall consistency here in the long run with all ctmods using `download_util` should be a bigger payoff I think.
Thanks!
> Steam-Play-None: Use `networkutil#download_file` for download logic

- pupgui2/resources/ctmods/ctmod_northstarproton.py
Noticed these when working on #518 :-)
> NorthStar Proton: Cleanup unused imports

- pupgui2/resources/ctmods/ctmod_vkd3dproton.py
This PR refactors the vkd3d-proton Ctmod to use the `download_file` util function. Previously it was using the legacy download logic that `download_file` was created to replace, which cleans up the file a little :-)
I tested that vkd3d-proton and vkd3d-lutris ([which subclasses the vkd3d-proton ctmod](https://github.com/DavidoTek/ProtonUp-Qt/blob/69fa871a25dae1838090cf2b433afef8e620f5e0/pupgui2/resources/ctmods/ctmod_vkd3dlutris.py#L14)) both download and extract correctly following this change.
Thanks!
> vkd3d-proton: Refactor to use `download_file`

- setup.cfg
This makes it easier to launch the GUI when installing from source.
https://setuptools.pypa.io/en/latest/userguide/entry_point.html
> Add entry point for GUI script
