DavidoTek/ProtonUp-Qt

share/metainfo/net.davidotek.pupgui2.appdata.xml

The current tag is incorrect and results in German translation being displayed as default.

appdata: fix translated summary

---

pupgui2/resources/ctmods/ctmod_z2dxvknightly.py

This PR adds support for DXVK git version in master branch as "DXVK (nightly)" in compatibility tool list, fixes #96. It'll install DXVK nightly as `dxvk-master-<commit long hash>` in Lutris.

feat: add support for DXVK git version.

---

pupgui2/resources/ctmods/ctmod_protontkg.py

It was a tough work, but it can download both new builds from CI and old builds from GitHub releases now. Currently CI builds is named after the workflow runs id (which doesn't really make sense for end user except that the largest number is the latest), and it's using Proton with Valve bleeding edge Wine (because I think Proton is best suited with Valve's Wine which contain patches for gaming), if you want to switch to Proton with Wine latest commit, tell me and I'll change it :P (Although I don't think there will be benefits in changing, since Wine master is just bleeding edge as Valve Wine)
Proton CI version when installed will be named as `proton_tkg_experimental.bleeding.edge.x.x.xxxx.YYYYMMDD`, this name is from the CI, I can't do anything to get this name before extracting (since …

feat: support Proton Tkg CI builds 

---

README.md

In #62 you converted ProtonUp-Qt to a Python module, but in README the command to run from source is still using old method (doesn't work anymore).

readme: change run command to run python module

---

pupgui2/util.py
requirements.txt

after a reboot, the previous pid written in the lockfile can be taken by other process, in this case, user will keep getting the "Second instance of ProtonUp-Qt found!" but actually there's no other instance. Setting custom process name and checking the process name will make it more accurate.

make single instance check more accurate

---

pupgui2/resources/ctmods/ctmod_z0dxvk.py

Fixes #138 
DXVK 2.0's release ships a new tarball for DXVK native. The logic in the DXVK ctmod doesn't account for this (as I believe previous releases just shipped the regular DXVK release). As a result, when downloading DXVK 2.0 with ProtonUp-Qt, the different folder structure incorrectly shows `lib` and `lib32` - the two folders in the DXVK native tarball - as compatibility tools.
This adds a check for the GitHub asset name having `native` anywhere in it, as with a name like that we can assume (at least currently) that this will only refer to the DXVK native builds.
According to the linked issue, DXVK Async doesn't have this issue. I am not sure about DXVK nightly, either. If we need to make changes here too, I can add those as well :-)
Thanks!

Fix DXVK 2.0 downloading DXVK native release

---

pupgui2/datastructures.py
pupgui2/pupgui2ctinfodialog.py

I was originally going to open an issue for this, but I decided to investigate to try and fix this issue instead. This PR solves the issue I mentioned in #137 with being unable to test Lutris games.
The Lutris compatibility tools list has a couple of issues:
- Sometimes, `installer_slug` is `None` and so a game file won't be found, since the logic tries to build a file string for the Lutris game yml config (so a filename could end up being `None-34496832234.yml`
- The label for the number of games using a Lutris compat tool was not set
This PR addresses both of these problems.
Instead of building a string, we now loop through all the files in the Lutris game config directory (`~/.config/lutris/games`) and when we find a filename that matches *either* the `slug` *or* the `installer_slug`, …

Lutris: Fix some games not being found

---

pupgui2/resources/ctmods/ctmod_d8vk.py

There is no corresponding issue for this PR, but it's something I thought would be a neat addition! :-)
[D8VK](https://github.com/AlpyneDreams/d8vk) is a project that that implements Direct3D 8 over Vulkan. It is a fork of DXVK. Quite a nifty project! If you remember the days of D9VK before that was upstreamed, it's the same idea. 
This PR adds support for downloading D8VK as a DXVK version for Lutris.
The D8VK ctmod is very similar to the DXVK nightly Ctmod and actually the DXVK nightly ctmod was used as a base.
D8VK does not distribute full "releases" at least not at the time of writing. Instead you have to download it from [GitHub Actions](https://github.com/AlpyneDreams/d8vk/actions). Luckily, the builds are very regular, but this is still a "nightly" build. For this reason, I kept …

Lutris: Add D8VK source

---

pupgui2/pupgui2.py
pupgui2/resources/ctmods/ctmod_vkd3dlutris.py
pupgui2/resources/ctmods/ctmod_vkd3dproton.py
requirements.txt
setup.cfg

Implements #73 
Adds support for downloading vkd3d for Lutris. Like with manual DXVK version downloads, this has to be entered manually in the Advanced Options for a Lutris game, but this is general Lutris usage and would apply if this was done manually as well :-)
Two sources are added here: [vkd3d-proton](https://github.com/HansKristian-Work/vkd3d-proton/) (the project used by Valve in Proton) and [vkd3d-lutris](https://github.com/lutris/vkd3d/) (a fork of this project with seemingly minimal changes, at least at the time of writing) - The latter is just a Lutris fork of upstream vkd3d-proton simply called "vkd3d" - This is slightly further behind than regular vkd3d-proton, and releases as a `.tar.xz` instead of a `.tar.zst` like vkd3d-proton does. 
The benefit of having both is the …

Lutris: Add vkd3d sources

---

pupgui2/constants.py
pupgui2/pupgui2ctinfodialog.py

Close https://github.com/DavidoTek/ProtonUp-Qt/issues/147
1. Add a `vdf_dir` to `Steam Flatpak` in `constants.py`
2. Change the code in `pupgui2ctinfodialog.py` from `else: self.update_game_list_lutris()` to `elif self.install_loc.get('launcher') == 'lutris': self.update_game_list_lutris()`

Fix compat tool game list for Steam Flatpak (CtInfoDialog)

---

pupgui2/resources/ctmods/ctmod_steamtinkerlaunch.py
pupgui2/util.py

Close https://github.com/DavidoTek/ProtonUp-Qt/issues/148
Use `/etc/os-release` if `/etc/lsb-release` not found.

Fix lsb-release not found

---

requirements.txt

Fixes #155.
The `steam` library for Python was updated yesterday to address an issue with the `parse_appinfo` function. The format of this changed on Steam's side and so the library had to be updated to accommodate this following commit https://github.com/ValvePython/steam/commit/abf65abff15385deb8ba05adaf4e312254fb435c.
Honestly I don't really understand what the changes here did but I can confirm it fixes the issue for me when running from source. Also from my armchair glance at the commit this should not have any breakages on Flatpak or require any sort of Python version bump. It is a fix but it doesn't seem to do anything *too* "magical" or extravegant that might break compatibility anywhere. My concern here is bumping from a minimum of `1.1.0` to a minimum of `1.4.4`. In testing …

Bump steam library version

---

pupgui2/resources/ctmods/ctmod_steamplaynone.py

Adds [Scrumplex's Steam-Play-None](https://github.com/Scrumplex/Steam-Play-None) compatibility tool.
Description:
```
Run Linux games as is, even if 
Valve recommends Proton for a game.
Created by Scrumplex.
Useful for Steam Deck.
```
Closes https://github.com/DavidoTek/ProtonUp-Qt/issues/152.

Add Steam-Play-None compatibility tool

---

pupgui2/resources/ctmods/ctmod_steamplaynone.py

As per [this commit](https://github.com/Scrumplex/Steam-Play-None/commit/42e38706eb37fdaaedbe9951d59ef44148fcacbf) in Steam-Play-None, renaming shouldn't be needed anymore.

Steam-Play-None: Don't rename internal name

---

pupgui2/constants.py
pupgui2/datastructures.py
pupgui2/pupgui2gamelistdialog.py
pupgui2/resources/ui/pupgui2_gamelistdialog.ui
pupgui2/steamutil.py

This PR adds functionality to show the status from [ProtonDB](https://www.protondb.com/) for a game.
- It will download the status summary for all installed games on each startup of ProtonUp-Qt
- Currently, you can display the "ProtonDB tier" by hovering the SteamDeck Compatibilty in the game list
- TODO: Maybe display the status in a separate column?

Add ProtonDB.com status

---

pupgui2/pupgui2.py
pupgui2/util.py

Had this idea as part of my comments on #163.
Adds an offline check and indicates when the user is offline in the StatusBar by showing a message like `ProtonUp-Qt 2.7.6 (Offline)`. It does this with a newly created `util` method called `is_online`. This pings a given host with a specified timeout using `requests`, and determines if a user is offline by returning False if either a `ConnectionError` or `Timeout` exception is raised. Otherwise we return `True`.
The default host is `google.com` because it has fairly reliable uptime and a short response time. The default timeout passed to requests is `10`. However `is_online` can take a `host` and `timeout` argument, to help keep it flexible (for example, if we need to ping `github.com` instead).
The logic for resetting the statusbar message …

Add Offline Indicator to StatusBar

---

pupgui2/pupgui2.py

Fixes a small oversight from #164.
In my tests for that PR I opened ProtonUp-Qt offline to make sure it came up with "(offline)", and then re-connected and opened the compat tool dialog. What I somehow didn't think about was pressing this button while offline. If you do this while offline, the status bar will get stuck on "Fetching releases..."
This just updates the conditional to only update the statusbar text if we can connect to the internet, using the `is_online` method.
There are a couple of other things around offline functionality to consider, like right now there is an error when trying to fetch information from GitHub about the compattool while offline. But those are other issues that as far as I can tell don't have any user-facing impact, they're just """ugly""" in the command …

Don't update statusbar to fetch releases when offline

---

pupgui2/resources/ctmods/ctmod_boxtron.py
pupgui2/resources/ctmods/ctmod_roberta.py
pupgui2/resources/ctmods/ctmod_steamtinkerlaunch.py

With *Python 3.11.1* and *PySide 6.4.0.1* following error occurs when the STL ctmod tries to display a question message box: `question_box_message(PyObject) only accepts 1 argument(s), 5 given!`
Does not happen with ProtonUp-Qt AppImage (*Python 3.8*, *PySide 6.2.4*)
Fixed by passing a tuple with arguments instead of the arguments as parameters.
```diff
- Signal(str, str, QMessageBox.Icon)
+ Signal((str, str, QMessageBox.Icon))
```

Fix Qt Signal error (use Tuple)

---

pupgui2/datastructures.py
pupgui2/steamutil.py

This fixes bug #175 . I tested it on my machine and everything seems to be working.
I do not see yet why we would actually need to compute the shortcut ids using the CRC-based algorithm, since Steam does it for us already.
So, please verify I did not miss anything. I batch updated all my games with the new change, and everything worked fine.

Add support to non-steam games

---

pupgui2/pupgui2ctinfodialog.py

In the `ctinfodialog`, sorting by Steam AppID doesn't work properly. I guess it tries to sort them as strings instead of numbers. The fix for this is a small change to set the data properly as an integer. In my tests, a call to `setData` *is* actually required, as just `QTableWidgetItem(int(game.get_app_id_str()))` results in an empty AppID column :shrug: 
My bad for missing this initially. No change should be needed on the Lutris side as Lutris is sorted by slugs, which are strings anyway. I think Steam even stores AppIDs as integers so there shouldn't be any problem with setting the data type as integer.
Thanks :smile:

Fix Steam AppID sort in ctinfodialog

---

pupgui2/resources/ctmods/ctmod_winetkg_vanilla_wine.py

Follow-up from discussion in #178, another component of #156 
Adds the ability to download Vanilla Wine as a runner for Lutris. It uses the build based on the [Ubuntu build system](https://github.com/Frogging-Family/wine-tkg-git/actions/workflows/wine-ubuntu.yml), as discussed in #178. This is gated behind advanced mode as builds of Wine based on vanilla Wine may be less compatible, and generally a user will *probably* want to use builds based on Valve Wine for gaming, likewise discussed in #178.
Not sure if we want anything further added to the description of the ctmod. I did consider adding a warning but that might be excessive, and a user in advanced mode should (ideally) know what they're doing :slightly_smiling_face: 
The process of creating the ctmod is actually exactly how I …

Lutris: Add Vanilla Wine

---

pupgui2/resources/ctmods/ctmod_protontkg_winemaster.py

Requested in a comment in https://github.com/DavidoTek/ProtonUp-Qt/issues/156#issuecomment-1426677052.
Adds support for Proton-tkg built against Wine Master when running in Advanced Mode. As far as I'm aware there is generally very little reason to want to use a build of Proton based on Wine Master, but there are *some* instances where it may have some fixes. The most recent that comes to mind is that supposedly builds of Wine 8.1 and newer fix issues with DOOM 3 BFG. Likely there were others that I am just unaware of too, but that's my justification for implementing this request :sweat_smile: 
I considered renaming the regular Proton-tkg tool we have but specifying may just be confusing for users. I'm not sure though, we could always mirror what we did for Wine-tkg and name it "Proton …

Add support for Proton-tkg (Wine Master)

---

pupgui2/constants.py
pupgui2/pupgui2gamelistdialog.py
pupgui2/resources/ui/pupgui2_gamelistdialog.ui

This PR fixes a couple of bugs introduced in #180, and adds a small feature that I figured out how to do in the process of fixing those bugs :smile: 
No screenshot this time as there isn't really much to "show" :sweat_smile: 
- **Critically**, fixes the ProtonDB rating text having the wrong flag, meaning it didn't display (needs `Qt.DispalyRole` instead of `Qt.UserRole`)
- Fixes items in the games list being able to be double-clicked and edited by setting `NoEditTriggers` in Qt Designer - I don't think this would cause any problems, but it's minor unwanted behaviour imo
- Adds double-click actions to cells in the Game List, similar to the "Show info" dialog
- For Game Name, opens the Steam store page - Lutris does not have the "Show games list" button
- For Anti-Cheat, open the Are We …

Game List Improvements

---

pupgui2/steamutil.py

This PR fixes Steam game soundtracks being parsed by ProtonUp-Qt and showing up incorrectly in the Games List dialog. It does this by skipping apps that are not stored in `/path/to/steamapps/common`.
**Before**:
**After**:
Steam allows you to download soundtracks you own into a specified library folder. While games tend to go into `/path/to/steamapps/common`, music conveniently goes to `/path/to/steamapps/music`.
The properties dialog in Steam for the soundtrack is virtually identcial to any other Steam app, *including* the ability to select a compatibility tool! This does... nothing, apparently! If you want to use Wine with your game soundtracks you'll have to buy it from the store apparently :-)
Steam does not seem to have a good way locally of differentiating between the types of …

Steam Apps: Don't fetch soundtracks as steamapps

---

pupgui2/constants.py
pupgui2/datastructures.py
pupgui2/lutrisutil.py
pupgui2/pupgui2.py
pupgui2/pupgui2gamelistdialog.py
pupgui2/resources/ui/pupgui2_gamelistdialog.ui

This PR adds a Games List for Lutris, adjusting the data displayed to be relevant to Lutris games :smile: It displays games from all runners except Steam (as we already display Steam games in the Steam games list dialog), and also has full sorting support to match the Steam games list. Because I really wanted a change of pace from writing Bash :sweat_smile: 
I implemented this in `pupgui2gameslistdialog.py`. There was some logic there already in preparation for a Lutris games list it seems. I'm a bit undecided if this is "better" than having a separate dialog, but the ctinfo dialog is shared, and as mentioned there was already some prep work for a Lutris games list, so I figured it was fine at least for now :-)
Instead of displaying the compatibility tool, Deck compatibility, Anti-Cheat …

Lutris: Add Basic Games List

---

pupgui2/steamutil.py

I introduced a small regression in #183 that I somehow did not catch. When an appmanifest didn't exist for a SteamApp, the entire app list loading would trigger the exception in `get_steam_app_list`, meaning a lot of tools were erroneously listed as unused.
I added a check before attempting to load the vdf file to ensure it is actually a valid file.

Fix Steam games list regression from #183

---

pupgui2/pupgui2gamelistdialog.py
pupgui2/steamutil.py

Initially the Games List really only managed Steam game stuff. Lutris recently got support for showing a Games List, and in future hopefully there will also be a Heroic games list.
No screenshot here as there should be no user-facing change, just "backend" changes :-)
This PR splits the ProtonDB fetching logic and the Anti-Cheat status logic out into separate functions in `steamutil`.  This is not really faster or anything as far as I can tell (nor does it appear to be any slower), but the hope is to make the games list a little bit cleaner. Instead of having all of this logic in the games list, it's separated out into utility functions.
This also introduces the possibility of fetching ProtonDB and Anti-Cheat status outside of the games list dialog if it's ever needed, though I don't know …

Games List: Move Steam-Specific Logic to steamutil 

---

pupgui2/datastructures.py
pupgui2/heroicutil.py
pupgui2/pupgui2.py
pupgui2/pupgui2ctinfodialog.py

Some work is a prerequisite for #168.
Implements support for showing an Info Dialog for Heroic Games compatibility tools :partying_face: To faciliate this, this also implements a `HeroicGame` datastructure, some associated utility functions and some other misc work around this.
This is heavily work-in-progress for the moment and has only seen light testing.
- No Epic Games integration - Not sure where the `library.json` file is (if it exists), what it looks like, etc
- However, if the Epic Games data is similarly structured then it should be trivial to include support!
- No Games List integration - It could go in a separate PR, I didn't want to work on it until #192 was merged
- I also have some other refactor work I want to submit for review for the games list dialog, and I don't want to …

Heroic: Add Info Dialog (GOG, side-loaded, Legendary)

---

pupgui2/constants.py
pupgui2/datastructures.py
pupgui2/heroicutil.py
pupgui2/pupgui2.py
pupgui2/pupgui2gamelistdialog.py

This PR implements #168, at least in a basic capacity :-) There is also some slight refactoring and additions to the fields stored in `HeroicGame`.
Here's the layout I came up with:
Note: There are no Legendary games in the screenshot as my test `installed.json` games don't have corresponding `GamesConfig/<app_name>.json` files, so they were showing up as native games, and so I decided to exclude them as this would not normally happen in practice.
The data for this list is fetched from a list of `HeroicGame`s. The Heroic Wine and Heroic Proton install locations share a gamelist, I felt that from a *user* perspective there is not much reason to split them up. In my mind I think it would be more frustrating to have to switch between each install directory just to see the games used. It …

Heroic: Add Basic Games List

---

pupgui2/pupgui2.py
pupgui2/pupgui2gamelistdialog.py
pupgui2/resources/ui/pupgui2_gamelistdialog.ui
pupgui2/resources/ui/pupgui2_mainwindow.ui

This PR does a few things:
- Show total installed tools for a given launcher beside its "Installed compatibility tools:" label.
- To the right of this, if there are any unused tools, display a label that says "Unused: {num_unused_tools}" (this is hidden if there are no unused tools).
- This currently only applies to Steam and Heroic, as there is no logic for checking unused Lutris tools
- On the Games List dialog, display the total found installed games.
- I originally thought to show this count in the dialog title, but in future this may not always be visible (i.e. if running in Steam Deck Game Mode), so I went with adding a label despite it taking up slightly more real-estate in the dialog than I'd like
It can be useful at a glance to see how many compatibility tools you have installed …

Show Tool Count on Main Menu, Show Total Installed Games on Games List DIalog

---

pupgui2/resources/ui/pupgui2_mainwindow.ui

It isn't immediately obvious at first glance what this button does, so this PR adds a tooltip that describes what the button does.
The rest of the UI imo is fairly self-explanatory and intuitive, and the user only has to click on this tool button to figure out what it does, but a tooltip is a nice quality-of-life improvement I think :-)

Add Tooltip to Custom Install Directory button

---

pupgui2/pupgui2.py

Adds the option to use `QKeySequence.Quit` to quit the application. Generally on Linux this is `Ctrl+Q` (for some command line stuff it can be `Ctrl+Shift+Q`). Though we could use `QShortcut(QKeySequence('Ctrl+Q'))`, it's generally better to use built-in `QKeySequence` values for shortcuts.
I had this idea when working on #204, and eventually figured out how to properly implement keyboard shortcuts. I'll look into updating how I did it in that PR too :-)
Thanks!

Add Quit Shortcut

---

pupgui2/pupgui2.py
pupgui2/pupgui2installdialog.py
pupgui2/util.py

Implement #206.
This is currently missing the shortcuts for the compatibility tools, but should have the rest as described in that issue:
- Add Compat Tool: `Ctrl+N`
- Add Install Location: `Ctrl+Shift+N`
- Remove Compat Tool: `Delete`, `Ctrl+Backspace` (for keyboards without delete key)
- About: `F1`, `Ctrl+,`
- Compat Tool Info: `Alt+Enter`
- Games List: `Ctrl+G`
For the compatibility tools, the `PupguiInstallDialog` could have a method to set the selected compatibility tool. We could then pass an optional parameter to `MainWindow#btn_add_version_clicked` which would specify the tool. A lambda something like this would  then be attached to the shortcut:
```python
def setup_ui(self):
QShortcut(QKeySequence('Ctrl+Alt+T'), self.ui).activated.connect(lambda: …
```

pupgui2: Add More Keyboard Shortcuts

---

pupgui2/pupgui2ctinfodialog.py
pupgui2/pupgui2gamelistdialog.py
pupgui2/resources/ui/pupgui2_ctinfodialog.ui
pupgui2/resources/ui/pupgui2_gamelistdialog.ui

This PR primarily adds a search box to the ctinfo dialog, available via a search button and a Ctrl+F shortcut, much like #204.
When the "Batch update" button is visible, it is temporarily hidden and the search box is shown, very similar to how #204 handled the Steam running warning label.
<hr>
This PR also does a couple of other smaller tweaks:
- Games List: Only enable searching (shortcut and button) is there are any games found
- Adjust focus setting for various UI elements, so that an inactive selected indicator is not displayed on some elements i.e. the games list
- Ctinfo: Convert `btn_close_clicked` to lambda, as this method only called `self.ui.close()`
<hr>
Tested this PR with the following tools:
- Steam
- GE-Proton
- SteamTinkerLaunch
- Luxtorpeda
- Lutris:
- Lutris-Wine …

Ctinfo: Add Search Box

---

pupgui2/pupgui2ctinfodialog.py
pupgui2/pupgui2gamelistdialog.py
pupgui2/resources/ui/pupgui2_ctinfodialog.ui
pupgui2/resources/ui/pupgui2_gamelistdialog.ui

With https://github.com/DavidoTek/ProtonUp-Qt/pull/211 and https://github.com/DavidoTek/ProtonUp-Qt/pull/214, caching of games has been enabled to increase the load times of the dialogs. This comes with the limitation that external changes are not registered, even when re-opening the game list or ctinfo dialogs.
This PR adds a refresh button to both the game list and the ctinfo dialog that updates the cached games and rebuilds the list of displayed games.

Add a Refresh Button to the Game List and Compat Tool Info dialog

---

pupgui2/pupgui2ctinfodialog.py

https://github.com/DavidoTek/ProtonUp-Qt/pull/215 added a refresh button to the ctinfo dialog.
This PR fixes that both the `Batch update` button and the Search bar should not be visible at the same time when clicking the refresh button.

Fix regression: Only show batch update button if search bar invisible

---

pupgui2/pupgui2.py
pupgui2/pupgui2installdialog.py
pupgui2/resources/ui/pupgui2_ctinstalldialog.ui
pupgui2/resources/ui/pupgui2_installdialog.ui

This PR converts the install dialog to use a Qt Designer `.ui` file. This is more consistent with the other dialogs that ProtonUp-Qt uses, and allows for some cleanup of the install dialog class.
This also has an indirect benefit: it works around a PySide6 bug with Plasma Wayland, where dialogs on scaled displays don't render correctly until moved to a non-scaled display and back again.
I attempted to keep the UI as close as possible to the existing install dialog but I did have to increase the size of the dialog just a small amount. On main, the dialog and its elements extend it to a size of `314x279`. However in Qt Designer, with the way it aligns elements, this meant that everything was slightly off-center; elements on the right had slightly more spacing than those on the left.
To …

Use UI file for Install Dialog

---

pupgui2/constants.py
pupgui2/pupgui2gamelistdialog.py

When clicking the button to fetch the ProtonDB rating, it focused the cell with the rating. This made the color less obvious as it would use the focus color which drowned out the rating color. This PR defocuses that cell after revealing the rating.
There is also a minor change to the color used for the gold rating to match the one used on ProtonDB (the other colors already matched), and to add a color for "pending" as on the system theme it was just black and not very visible. Though to be honest I am not totally happy with the color - I tried to go for something distinct enough to stand out (though not obnoxiously so) and different enough to distinguish it from the other ratings. If there is a better color in mind please suggest/change it directly :-)
Thanks!

Games List: Unfocus ProtonDB Rating after Click

---

pupgui2/steamutil.py

Related to #226.
This moves the `if not no_shortcuts` check inside the `try` block to prevent a crash if `c` is not assigned. If something inside the `try` block fails early on, the libraryfolders VDF (`v`) or config VDF (`c`) variables may not be set appropriately and so a crash will occur when trying to reference `c` before it is assigned a value - If `v` throws an exception then `c` will never be set, or `c` is not loaded properly it could also be `None`. If the VDF library can read it though it should always return an empty dict, but if any of the `get`s fail it could end up being `None` I think (not sure, never had an exception get thrown with chained `get`s, not sure if it will just be `None`, take on the last return value, or if it will be unassigned thus triggering the crash). …

steamutil: Move shortcuts check inside try block, add logging for VDF file loading

---

pupgui2/resources/ctmods/ctmod_d8vk.py

[D8VK apparently uses `main` as its default branch now](https://github.com/AlpyneDreams/d8vk/branches), which breaks the download check. Since it skips any workflows that aren't based on the `head_branch` being `master` it was skipping all of them and not fetching any releases.
I'm not sure when the branch name changed but when investigating an implementation of D8VK for Heroic I came across this issue (not in this PR). D8VK seems to work fine now with this change.

D8VK: Update branch name

---

pupgui2/pupgui2.py
pupgui2/pupgui2customiddialog.py
pupgui2/pupgui2installdialog.py
pupgui2/resources/ui/pupgui2_custominstalldirectorydialog.ui
pupgui2/util.py

I had some time so I decided to take a look at overhauling the custom install directory dialog, making several small tweaks that turned out to be quite an overhaul. This is not yet complete but I made enough progress that I'm ready to open it and get some feedback :-)
This PR overhauls the Custom Install Directory dialog in a number of ways:
- Convert the dialog to use a `.ui` file - This doesn't reduce the size of the file in the end but allows for consistency with the other dialogs.
- Add a short description on the purpose of this dialog - Phrasing improvements welcome! 
- Add a "Close" button, which allows for the dialog to be closed when running in GameScope (i.e. on Steam Deck).
- Add a "Default" button, which takes the place of the "Reset" functionality previously coupled to the …

Custom Install Directory Dialog Overhaul

---

pupgui2/resources/ctmods/ctmod_protontkg.py
pupgui2/resources/ctmods/ctmod_protontkg_winemaster.py
pupgui2/resources/ctmods/ctmod_winetkg_valve_otherdistro.py
pupgui2/resources/ctmods/ctmod_winetkg_vanilla_wine.py

Implements part of a request from #232 to add Wine-tkg sources to Heroic, and also includes Proton-tkg sources for Heroic as well.
Only Lutris supports Wine-tkg sources, and Steam only supports Proton-tkg sources. This PR enables Wine-tkg downloads for Heroic Wine, as well as Proton-tkg for Heroic Proton. Let the Heroic frogs be free! :frog: 
I explained in #191 that Proton isn't *really* meant for use outside of Steam, but for Heroic Proton we already facilitate downloading GE-Proton. Heroic has been acting up a little for me and it's a bit late at time of writing so I haven't checked, but I think Heroic actually looks for the Steam Linux Runtime when using Proton (which is a little unconventional, but SteamTinkerLaunch does the same, so it should be fine). I am not certain that Lutris …

Heroic: Add Wine-tkg and Proton-tkg sources

---

pupgui2/resources/ctmods/ctmod_protontkg.py

Partially Fixes #236.
The GitHub API call to fetch workflow runs for Proton-tkg was not taking into account the `count` parameter given to the `__fetch_workflows` method. This PR fixes that by passing a `per_page={count}` to the API call. The API URL will now look something this like: https://api.github.com/repos/Frogging-Family/wine-tkg-git/actions/workflows/29745300/runs?per_page=100
This was discovered to be causing issues as the "Proton-tkg (Wine Master)" CI has had a significant number of failures recently, so ProtonUp-Qt was falling back to only displaying the releases.  By default, this API only displays the last 30 builds. Since ProtonUp-Qt filters to only show successful builds (as there are no build artifacts for failed builds), and the last 30+ builds have failed, the `tags` …

Proton-tkg: Pass count arg when fetching workflow runs

---

pupgui2/pupgui2customiddialog.py

Minor QOL change I thought to make when messing around with the file picker dialog. Instead of just saying "Find Directory" it is now a little bit more descriptive (which is good for users who are like me and might forget what they opened the dialog to do...)
Before:
After:
Note: I'm not sure what this might do on Flatpak, because when running the Flatpak, ProtonUp-Qt appears to use xdg-portals to open the file dialog. Portals are, in short and in this instance, a way to have consistent cross-desktop file dialog behaviour by basically telling the desktop to "plug in" it's file dialog in place of one an application might use as a fallback, i.e. use a GTK file picker on GNOME. Portals can be used in other ways (such as for audio/screen sharing afaik) but the file picker is what we are …

CID: Set title for file dialog

---

pupgui2/pupgui2.py
pupgui2/resources/ctmods/ctmod_d8vk.py

This PR adds support for installing D8VK for Heroic, as requested in #208.
Heroic stores DXVK versions in its `tools` directory, under the `dxvk` folder. The folder structure of DXVK versions that it expects matches Lutris and so no change was needed to the extraction logic. It simply expects a folder in the `tools` directory with the name of the tool, and then the `x32` folder for the required DLLs.
Though this PR Is for *D****8****VK*, this project is a fork of DXVK and operates similarly, so from Heroic's perspective D8VK would be treated as a separate DXVK "version" :-)
Two main changes were needed for this PR:
1. Updating `ctmod_d8vk` to check which directory to extract into using some checks in the current launcher's path. For Heroic and Lutris we have two different extraction …

Heroic: Add D8VK

---

pupgui2/resources/ctmods/ctmod_lutriswine.py

Fixes #256, mostly. It doesn't fix an issue with the download/extraction getting stuck at 99%, because I couldn't reproduce that, but it should fix the user getting to the point where they could download an invalid build.
Right now ProtonUp-Qt assumes that Lutris-Wine builds all have an associated fshack build. The fshack is a Wine patch, and I guess for compatibility reasons, older Wine builds came patched with and without it. As of [Lutris-Wine 7.2-2](https://github.com/lutris/wine/releases/tag/lutris-wine-7.2-2) (distinct from [Lutris-Wine 7.2](https://github.com/lutris/wine/releases/tag/lutris-wine-7.2), which **does** have the fshack build available), this is no longer required. The fshack in Lutris-Wine >= 7.2-2 can be controlled with an environment variable: …

Lutris-Wine: Only show fshack build when the release has it

---

setup.cfg

The `install_requires` dependencies for `setup.cfg` mostly match that of `requirements.txt`. The only exception is the `steam` library which is still at `1.1.0`, when really it should be `1.4.4` (as this has the updated magic for VDF parsing, see #157). This PR bumps that requirement version.
This hasn't affected anything and `>= 1.1.0` should probably always use the most up-to-date `steam` dependency, I can't envision a reasonable case when it wouldn't without explicit user intervention. I don't think there's any harm in keeping these in sync, though.
I believe `setup.cfg` is used by setuptools, though I am not exactly sure how this file applies in that context to ProtonUp-Qt.

Bump steam dependency version to match requirements.txt

---

pupgui2/resources/ctmods/ctmod_protontkg.py
pupgui2/util.py

Fixes two issues I (introduced and) found while testing the v2.8.1 Flatpak. They are not specific to Flatpak, I just found them during testing flathub/net.davidotek.pupgui2#18.
This is due to a bug where the default mode is `r` and gets garbled into `r:r`. This produces the error "unknown compression type 'r'". This happens because `if not mode.startswith('r:')` then we set it to `r:{mode}`. When the mode is left to the default parameter, which is `r`, this gets garbled to `r:r` (because `{mode}` is `r`). Having `r` on its own is also a valid argument to `tarfile.extractall`, but changing the default parameter to `r:` is very "elegant" and doesn't require any refactoring.
The fix for this bug is to set the default parameter to `r:`. Setting `r:*` is also valid. When having the default as …

(v2.8.1 fix) Default tar extract mode to 'r:', remove successfully extracted tkg archives

---

pupgui2/resources/ctmods/ctmod_protontkg_winemaster.py
pupgui2/resources/ctmods/ctmod_winetkg_valve_otherdistro.py
pupgui2/resources/ctmods/ctmod_winetkg_vanilla_wine.py

Removes some duplicated variables from the Proton-tkg subclasses, like the buffer size and signal. These are already set by the main Proton-tkg class and the values didn't change for the subclasses, so we don't need to set them.
Did a quick spot check and this didn't break anything, Tkgs still downloaded successfully for Lutris, Heroic and Steam.
This is just minor code maintenance, and has no impact on functionality. So no screenshots for this one :-)

Proton-tkg: Remove unnecessary variables from subclasses

---

pupgui2/resources/ctmods/ctmod_vkd3dlutris.py
pupgui2/resources/ctmods/ctmod_vkd3dproton.py

vkd3d-lutris now inherits from the vkd3d-proton ctmod, changing only the CT_URL and CT_INFO_URL to point to the right location. This essentially removes all logic from vkd3d-lutris and the only thing it does is set its own CT_NAME etc, and its own URLs. inside the class, so that other method calls inside this class point to the correct vkd3d-lutris URLs. This is very similar to how Proton-tkg ctmods are implemented.
I'll be referencing the Proton-tkg a bit here, because it's got a similar approach. 
vkd3d-proton has been updated to allow extracting both `.tar.zst` archives (vkd3d-proton) and `.tar.xz` archives (vkd3d-lutris). The check in `__fetch_github_data` also had to be updated, it was checking if the asset name ended with `.tar.zst` so I changed it to check for both archive formats. …

vkd3d: Make vkd3d-lutris inherit from vkd3d-proton

---

pupgui2/resources/ctmods/ctmod_z0dxvk.py

This adds DXVK for `heroicwine` and `heroicproton`, mirroring the implementation for #245. I tested that this didn't break Lutris, and tested a couple of different DXVK versions (v2.2 and v2.0) for each.
DXVK versions are displayed on the main menu without any changes, because #245 added the logic to check for and display DXVK and vkd3d tools. The only change required here was changing the path that DXVK is extracted to.
An equivalent change can be made for VKD3D as well, though that can go in a separate PR that will depend on whether #262 is accepted or not ;-) 
Thanks!

Heroic: Add DXVK

---

pupgui2/resources/ctmods/ctmod_vkd3dlutris.py
pupgui2/resources/ctmods/ctmod_vkd3dproton.py

Adds vkd3d-lutris and vkd3d-proton for heroicwine/heroicproton, similar to https://github.com/DavidoTek/ProtonUp-Qt/pull/263
> sonic2kk: An equivalent change can be made for VKD3D as well, though that can go in a separate PR that will depend on whether # 262 is accepted or not ;-)

Heroic: Add vkd3d

---

pupgui2/constants.py
pupgui2/pupgui2gamelistdialog.py

When double-clicking the AreWeAntiCheatYet.com status in the gamelist dialog and the awacy status is known, the awacy site is opened with only the selected game displayed (game name in search).
If the status of the game is not known, https://areweanticheatyet.com/ will open normally.
Search URL: https://areweanticheatyet.com/?search={GAMENAME}&sortOrder=&sortBy=

Gamelist: Search game on AWACY when double-clicking status

---

pupgui2/heroicutil.py

Heroic recently introduced support for Amazon Games, in the v2.9.0 release a few days ago. This PR add support for listing installed Amazon Games in the Heroic Games List.
All games marked as "nile" are the Amazon Games. Internally, Heroic refers to Amazon Games as "Nile" games, pretty clever!
As a quick recap on how the existing GOG, sideload and Legendary games work (#168 has a more in-depth breakdown):
- Every Heroic game has a unique identifier string called `app_name`. GOG, sideload and Legendary have different formats (GOG typically uses numbers, sideload and Legendary typically use an alphanumeric string).
- Sideload and GOG games store information in `/path/to/heroic/sideload_apps/library.json` and `/path/to/heroic/gog_store/library.json` - These store basic game information such …

Heroic: Add Amazon Games to Games List

---

pupgui2/heroicutil.py
pupgui2/pupgui2gamelistdialog.py

Heroic v2.9.0 added a feature for adding Browser games to your library. This works by giving the game a name, path, and a URL. Heroic will then run this game in its Browser, which is Chromium (with a spoofed browser agent to act like Google Chrome afaik).
ProtonUp-Qt can display these, but this PR fixes up their entries to make them a bit more useful.
Main branch:
This PR:
Browser games are treated internally like sideloaded apps, with their information stored in the `sideload_apps.json` file. They also still have an `app_name`. So there were no code changes required to get Browser games to display. Right now, ProtonUp-Qt _will_ display these browser games in the Heroic Games List, but with a couple of problems:
1. Compatibility Tool is listed as "Not Found", because Browser games …

Heroic: Correctly display Browser games in Games List

---

pupgui2/resources/ctmods/ctmod_d8vk.py

D8VK has changed how it builds and thus names artifacts, and so newer builds are not being detected with ProtonUp-Qt. This PR fixes the issue and allows newer D8VK builds to download again by checking on the new `dxvk` artifact name, whereas previously we checked on `d8vk`.
Originally, D8VK builds packaged two artifacts:
- `d8vk-<branchname>-hash`, which represents the actual D8VK build and is only a few MBs. This has always been the artifact that we wanted, as this is has the D8VK DLLs for use with Proton.
- `dxvk-<branchname>-hash`, which represents the DXVK native builds introduced with DXVK 2.0. This contains Linux libraries which can be used by game developers to package DXVK (or in this case, D8VK) as a native library for native Linux games (for an example of DXVK doing this, Portal …

D8VK: Fix fetching new artifacts

---

pupgui2/steamutil.py

For some reason, my steam deck has AppName as lowercase in the .steam/steam/userdata/xxxxx/config/shortcuts.vdf
This is a quick fix that supports both uppercase and lowercase variations.

Fixed non steam game names not shown

---

AppImageBuilder.yml
pupgui2/constants.py
setup.cfg
share/metainfo/net.davidotek.pupgui2.appdata.xml

Release includes:
- Fix Tkg Tar file extraction regression from 2.8.1 #267 (already included in Flatpak, not yet in official release https://github.com/DavidoTek/ProtonUp-Qt/issues/261#issuecomment-1666538892)
- DXVK for Heroic #263 
- vkd3d for Heroic #268 
- Amazon Games for Heroic #271 
- Browser Games for Heroic #272 
I will see if there is anything else we can include, otherwise I will merge this soon.

Bump version to 2.8.2

---

pupgui2/resources/ui/pupgui2_mainwindow.ui

I noticed there were strings that didn't need to be translated in the .ts files.
I didn't regenerate the .py file from the .ui file because, while not knowing how to name it, 
I don't want to mess up the project naming scheme your are currently using.

Removed translatable check on strings

---

pupgui2/steamutil.py

Fixes an issue where Proton Next shows up as a game in the Games List, but it is not actually a game. We do this by explicitly skipping its AppID in [`update_steamapp_info`](https://github.com/DavidoTek/ProtonUp-Qt/blob/ac97072a0b42fd5f892be2d320819235b14a5921/pupgui2/steamutil.py#L238), should it be missing from `ctool_map`. It will only be missing from `ctool_map` if there is no current Proton Next version in testing.
Occasionally, Valve will release a "Proton Next" build, which essentially serves as a Release Candidate build of Proton. Despite what the name might imply, this is only used for a Release Candidate and not as a general early-access release, that is more along the lines of Proton Experimental (or its various Bleeding Edge branch betas) or Proton Hotfix for specific game …

steamutil: Don't parse Proton Next as a game

---

pupgui2/pupgui2.py

With PySide 6.5.2, `QGuiApplication::setDesktopFileName` expects the id without suffix `.desktop`:
```yaml
Platform: KDE Flatpak runtime 6.5 Linux-6.2.0-32-generic-x86_64-with-glibc2.35
QGuiApplication::setDesktopFileName: the specified desktop file name ends with .desktop. For compatibility reasons, the .desktop suffix will be removed. Please specify a desktop file name without .desktop suffix
```
```diff
- app.setDesktopFileName('net.davidotek.pupgui2.desktop')
+ app.setDesktopFileName('net.davidotek.pupgui2')
```

Remove Qt .desktop file prefix

---

pupgui2/datastructures.py
pupgui2/pupgui2gamelistdialog.py
pupgui2/pupgui2shortcutdialog.py
pupgui2/resources/ui/pupgui2_gamelistdialog.ui
pupgui2/resources/ui/pupgui2_shortcutdialog.ui
pupgui2/steamutil.py
pupgui2/util.py

This PR adds a Shortcut Editor for Steam (both Native and Flatpak supported).
Currently, editing the App Name, Executable Path, Starting Directory and App Icon is supported.
- Mark shortcut (red text) and delete it after pressing `Save`
- Determine a user for new shortcuts like this: Check if there are already other shortcuts
- If there are: Use the most common user across the other shortcuts
- Otherwise: Determine which Steam user was most recently logged in
- If there isn't any Steam user (e.g. fresh install): Return and don't do anything - currently no user feedback
- Add a tool button that lets the user choose an executable/directory using a file dialog
- Modify the available columns / let the user choose
- Fix the Start In field automatically: …

Add a Steam Shortcut Editor

---

pupgui2/resources/ctmods/ctmod_northstarproton.py

Northstar Proton has been migrated to the R2NorthstarTools organization
Also fixes the capitalisation of Northstar and Titanfall 2

Update NorthstarProton URL

---

pupgui2/resources/ctmods/ctmod_steamtinkerlaunch.py

FIxes #300.
There is an AUR package called `xwinfo` ([repo](https://github.com/baskerville/xwinfo)), which seems similar (equivalent?) to `xwininfo`. When installing SteamTinkerLaunch, if ProtonUp-Qt can't find `which xwininfo`, instead of using this name, displays the `xwininfo` dependency name as `xwinfo`. Even if `xwinfo` is installed it will not return anything for `which xwininfo`, as its command name is `xwinfo`. SteamTinkerLaunch also expects to find a command `xwininfo`, it is not compatible with `xwinfo`. It could be possible for SteamTinkerLaunch to use `xwinfo` if it is truly equivalent to `xwininfo`, but I'd honestly rather stick to official packages only for a dependency like this.
This PR fixes the SteamTinkerLaunch dependencies screen to now show `xwininfo` as the …

SteamTinkerLaunch: rename 'xwinfo' to 'xwininfo'

---

pupgui2/util.py

May help with #303.
When skimming the code and doing tests on my own PC for #303, I noticed requests was coming back with a `<Response [404]>`. Turns out the repos endpoint doesn't exist, or no longer exists. This doesn't break `is_online`, as we don't care about the status code, we just care that we can reach `api.github.com`. But I figured it might be better practice to hit a valid endpoint.
One user reported that ProtonUp-Qt will report that they are offline for them no matter what. Since `is_online` simply uses requests to ping an endpoint with a given request, I have two theories:
1. They are rate-limited, but I don't think `requests` would throw a `ConnectionError` for a rate limt, and it's even less likely that they would throw a `Timeout` (these are the two exceptions we check …

util: Use GitHub rate_limit endpoint with greater is_online timeout

---

pupgui2/datastructures.py
pupgui2/resources/ctmods/ctmod_00winege.py
pupgui2/resources/ctmods/ctmod_d8vk.py
pupgui2/resources/ctmods/ctmod_vkd3dproton.py
pupgui2/resources/ctmods/ctmod_z0dxvk.py
pupgui2/util.py

Implements #294.
This adds an extra step to Wine-GE installation which renames the extraction folder to be consistent with what the current launcher would name it.
Screenshots for Lutris and Heroic respectively:
We currently keep the name of the top-level archive (`lutris-GE-ProtonX-YY-x86_64`), but Lutris and Heroic do not use this name. For Lutris specifically, this apparently breaks auto-updating. For Heroic, I figured if we're making a change to be consistent for one launcher (Lutris) we should do it for all of them :-)
The launcher check is similar to what we use for DXVK (and elsewhere I believe), essentially checking for strong clues in the path to infer the launcher.
I am not sure what Bottles uses, as I don't use it, but if we need to make a change there it should be easy enough …

Wine-GE: Match launcher naming schemes on extract

---

pupgui2/constants.py
pupgui2/pupgui2.py
pupgui2/resources/ctmods/ctmod_z0dxvk.py
pupgui2/resources/ctmods/ctmod_z1dxvkasync.py
pupgui2/util.py

~~*(NOTE: This PR is still in draft and not quite ready for testing just yet, while I work out a couple of remaining trouble areas with the archive we download from GitLab, the description of this PR should be pretty final but is mostly written up so I can document the work I have done thus far and amend as I go :slightly_smiling_face:)*~~
PR should be in a working state and ready for review now :-)
<hr>
Implements #243.
This PR implements downloading the new DXVK Async project by Ph42oN from GitLab, replacing the `dxvk-async` project on GitHub by Sporif which is incompatible with newer DXVK versions.
The `dxvk-async` project on GitHub that we currently point to no longer sees active development. To my understanding, a change was introduced in upstream DXVK around v2.0 that broke …

DXVK: Update dxvk-async to use Ph42oN GitLab repo

---

pupgui2/pupgui2.py
pupgui2/resources/ctmods/ctmod_00protonge.py
pupgui2/resources/ctmods/ctmod_00winege.py
pupgui2/resources/ctmods/ctmod_boxtron.py
pupgui2/resources/ctmods/ctmod_d8vk.py
pupgui2/resources/ctmods/ctmod_kron4ekvanilla.py
pupgui2/resources/ctmods/ctmod_lutriswine.py
pupgui2/resources/ctmods/ctmod_luxtorpeda.py
pupgui2/resources/ctmods/ctmod_northstarproton.py
pupgui2/resources/ctmods/ctmod_protontkg.py
pupgui2/resources/ctmods/ctmod_roberta.py
pupgui2/resources/ctmods/ctmod_steamplaynone.py
pupgui2/resources/ctmods/ctmod_steamtinkerlaunch.py
pupgui2/resources/ctmods/ctmod_vkd3dproton.py
pupgui2/resources/ctmods/ctmod_z0dxvk.py
pupgui2/resources/ctmods/ctmod_z1dxvkasync.py
pupgui2/resources/ctmods/ctmod_z2dxvknightly.py

Currently, all ctmods share a single requests session which may contain the authorization header for GitHub. With #302, fetching compatibility tools from GitLab is now possible too. This requires ctmods to be able to choose between the GitHub and GitLab authorization key.
This PR does following changes:
- Each ctmod has its own requests session
- The ctmods will read the authorization keys from `main_window.web_access_tokens` and build a header using `util.py#build_headers_with_authorization` which is added to the local requests session
See https://github.com/DavidoTek/ProtonUp-Qt/pull/302#issuecomment-1808909601 for details

Move requests session to ctmods

---

pupgui2/pupgui2.py
pupgui2/util.py

This PR implements the backend for #305, it does not contain any GUI changes.
Right now we pass GitHub (and GitLab) access tokens via an environment variable. This works, but it has to be appended every time. On one hand, this is not so bad because tokens expire, but on the other hand until they expire (which could be months) if you want to keep using them to avoid a rate limit, you have to append them as an environment variable. For Flatpak, this can be configured from a tool to set Flatpak environment variables, such as Flatseal.
However it was requested to read these values from the config file instead. This PR implements the ability to read these variables from the config file instead of having to pass them as environment variables. Right now the main benefit to this is that it's more …

Config: Read GitHub and GitLab tokens from Config File

---

pupgui2/util.py

This PR replaces the logic in `util#config_theme` and `util#config_advanced_mode` to use the generic function `util#read_update_config_value` from #306, a change which was discussed in passing in that PR.
The logic in these functions was used as a template to create `read_update_config_value`, so there should be no compatibility breaking changes. The option names are also have not been changed. This change just makes the code slightly cleaner :-)
This PR does not touch `install_directory` or `config_custom_install_location`, as discussed we could implement this in future if we feel we need such a change.
Thanks!

Config: Use read_update_config_value for advancedmode and theme

---

pupgui2/pupgui2.py
pupgui2/pupgui2exceptionhandler.py

Fix https://github.com/DavidoTek/ProtonUp-Qt/issues/247
Adds a GUI exception handler, similar to the [implementation in the Rare game launcher](https://github.com/Dummerle/Rare/blob/76df1236e9d6a8ec122b293858c90330e6bb2fe3/rare/widgets/rare_app.py#L19-L41).

Add GUI exception handler

---

pupgui2/constants.py
pupgui2/pupgui2aboutdialog.py

This PR refactors the about dialog to be a little bit more concise. There is a significant change to the version check which we may need to discuss/revert, but I put it up like this as if it does work, it would be a lot simpler and more readable than what was there before :-)
The main idea behind this refactor is to make the code a bit more concise and easier to work in, as we may be changing this soon to accommodate other UI elements and related logic, or doing a significant change to turn it into a settings dialog. The idea is to just make this a little bit nicer to work in and """more consistent""" with the other UI classes, consistency as in using lambdas for `.clicked.connect` etc to replace class methods which are only used for this action.
This PR refactors
- Move themes to be in …

About Dialog: Refactor

---

pupgui2/resources/ctmods/ctmod_boxtron.py
pupgui2/resources/ctmods/ctmod_luxtorpeda.py
pupgui2/util.py

This PR updates the Boxtron ctmod to use a subclass of the Luxtorpeda ctmod, stripping it out almost entirely and having a couple of tweaked values. A new helper method was added to facilitate generating the dependencies warning message, and Luxtorpeda's `is_system_compatible` method was tweaked a little bit so that it could be called by subclasses. This saves subclasses having to implement this themselves and has as little repeated code as possible.
I chose Luxtorpeda as the primary ctmod as it was the most "generic". It didn't have any dependencies and did a lot of what Boxtron did, but without the dependencies check. In my mind this made it the ideal candidate to be the superclass, it has the fewest moving parts.
Luxtorpeda, Roberta, and Boxtron are all sister projects (with Luxtorpeda …

Boxtron: Use Subclass of Luxtorpeda

---

pupgui2/resources/ctmods/ctmod_luxtorpeda.py
pupgui2/util.py

Supersedes #310.
Updates Luxtorpeda to use the new `fetch_project_releases` and `fetch_project_release_data` util functions from #302. This reduces repeated code and will help "proof out" how these functions can be used in other ctmods. More work may be required for some ctmods, but for Luxtorpeda, it was a drop-in replacement.
Boxtron gets this for free because it subclasses Luxtorpeda as of #311, and Roberta will inherit this PR's changes when #317 is merged. That's why I didn't touch that ctmod in this PR, changing Luxtorpeda will change all of them. [Luxtorpeda](https://github.com/luxtorpeda-dev/luxtorpeda/releases), [Roberta](https://github.com/dreamer/roberta/releases/), and [Boxtron](https://github.com/dreamer/boxtron/releases/) all use `.tar.xz` archives, so the `release_format` …

Luxtorpeda: Use fetch_project_releases and fetch_project_release_data

---

pupgui2/resources/ctmods/ctmod_northstarproton.py

Same as #318 but for Northstar Proton.
Should still download and extract correctly, once again with no user-facing changes. Just code maintenance mostly :-) With the hope of moving as many ctmods over to this as possible, gradually so as to reduce the risk of regression in a monster PR :slightly_smiling_face:

Northstar Proton: Use fetch_project_releases and fetch_project_release_data

---

pupgui2/resources/ctmods/ctmod_kron4ekvanilla.py

Mostly the same as #318 but for Lutris' Kron4ek Wine-Builds Vanilla.
The difference here is that, like for DXVK, we have an asset condition that we pass. We only want to fetch 64bit, non-staging releases, so the existing conditional we had in `__fetch_github_data` to check the asset name was replaced with a lambda that we pass to `fetch_project_release_data`. This takes care of filtering the assets.
I tested with and without this conditional, and we end up with the `-x86` version, so this should confirm that the asset check works for us here :slightly_smiling_face: 
Once again, there should be no user-facing change and everything should still work as expected. The releases dropdown should have no change from `main`, and the correct archive should still download and extract correctly.
<hr> …

Kron4ek Wine: Use fetch_project_releases and fetch_project_release_data

---

pupgui2/util.py

Revise the i18n inside the `create_missing_dependencies_message` util function introduced with https://github.com/DavidoTek/ProtonUp-Qt/pull/311.
I apparently missed that one the format was misplaced inside the bracket. That will be fixed.
Where I'm already add it, this PR changes the message to be only one. This will make the translation simpler. (Note: There are some cases where a "split" translation makes sense, e.g. if the first part is the same, and the later part is different)
```python
QCoreApplication.instance().translate(
'util.py',
'You need {DEPS} for {CT_NAME}.'.format(DEPS=', '.join(dependencies), CT_NAME=ct_name)
)
QCoreApplication.instance().translate(
'util.py',
'You need {DEPS} for {CT_NAME}.'
).format(DEPS=', '.join(dependencies), CT_NAME=ct_name)
tr_raw_msg = …
```

util: revise i18n of create_missing_dependencies_message

---

pupgui2/datastructures.py
pupgui2/pupgui2.py
pupgui2/steamutil.py

Addresses at least part of #254.
This PR adds `(global)` beside installed compatibility tools which are set as the global tool in the Steam client's Steam Play settings. When no compatibility tool is forced, but when Steam detects that a game/app is a Windows-only application, this is the default tool that will be used to run that app from the Steam Client. This can be any compatibility tool, including things like GE-Proton. In such a case, even though the compatibility tool is technically not *explicitly* used, it is still the default and so used by all Windows games which do not have an alternative compatibility tool forced in the Properties dialog.
This PR accomplishes marking the tool as global, in summary, by doing the following:
- Adding a property `is_global` to `SteamApp`. This is …

Tool List: Mark Tool as Global

---

pupgui2/pupgui2.py

Another part for #254, and hopefully a quick win.
This PR puts the global compatibility tool at the top of the tools list. We do this in the same condition here we mark the tool as global. I found a one-liner on StackOverflow that shows how to do this. Since we're looping through the `compat_tool_index_map` list already, we have a reference to the `ct` object. So we `pop` it from the list and since `pop` returns the element, we can pass this to `insert` and put it at index `0`. Maybe not the *most* readable one-liner but I think it's fine :-)
This doesn't impact interacting with the tool the ctinfo dialog still opens as expected (we can make the change to hide the Games List after #319):
*(The games list is displaying this way because I edited my `config.vdf` temporarily, with Steam …

pupgui2: Put Global Tool at top of list

---

pupgui2/pupgui2ctinfodialog.py
pupgui2/resources/ui/pupgui2_ctinfodialog.ui

UX tweak related to #254.
Follow up from #319.
This PR hides the games list for the global compatibility tool. Currently this only applies to the Steam global compatibility tool. This is because this tool is the default for any game not using a custom compatibility tool, so it doesn't really make sense to show a games list, and any games list we show would be incomplete, and there's no need to show the list when a given tool is the global one.
I also made a minor change to set the focus to be the "Close" button when the games list is blank or when the tool is global.
*(The number of games using the compatibility tool is `5` because I modified my `config.vdf` to set this tool as global instead of actually setting it as global from Steam, to avoid messing up any game configurations, since I …

CtInfo: Hide Game List When Tool is Global

---

pupgui2/pupgui2.py
pupgui2/steamutil.py

`map` is a keyword, so this PR replaces a couple usages of `map` as a variable name to avoid that, and hopefully uses clearer variable names for this as well :-)

misc: Avoid shadowing 'map' name

---

pupgui2/pupgui2shortcutdialog.py
pupgui2/resources/ui/pupgui2_shortcutdialog.ui

This PR adds a QLineEdit to function as a search bar to the Shortcuts Editor dialog, matching what we have for the CtInfo dialog and the Games List dialog. I have some other planned PRs for the Shortcuts dialog (spoiler :wink:) , so while I was working in here I realised search was missing and figured it would be straightforward enough to add.
Unlike the CtInfo and Games List tables, which use static labels, the Shortcuts Editor uses QLineEdits. So in order to search, we have to get the widget in the cell and then get the text from that widget, instead of just getting the TableItem at that cell and getting the text.
I believe you can populate tables with TableItems in Qt and have the option to double-click to edit them, but the Shortcuts Dialog uses QLineEdits and personally I think this …

Shortcut Editor: Implement Search Functionality

---

pupgui2/pupgui2ctinfodialog.py
pupgui2/pupgui2gamelistdialog.py
pupgui2/util.py

This PR allows for dynamically setting the search box tooltip for the CtInfo Dialog and Games List. On `main`, we hardcode these in the UI file to "Half-Life 3" and "Team Fortress 2" respectively, but now we attempt to take a random game from the list of games and use that game name in the tooltip. For example, if the games list has "GUILTY GEAR -STRIVE-", the tooltip has a chance of selecting that game and so would say "e.g. GUILTY GEAR -STRIVE-".
If the game list length is zero, or if we happen to select a game that somehow doesn't have a name, we will fall back to the default tooltip defined in the UI file. There could *maybe* be an edge case for Heroic/Lutris if someone only had one game using a tool and they manually made the game name blank, in such a case we would use our fallback. …

CtInfo, Games List: Use random game name from list in tooltip

---

i18n/pupgui2_de.ts
i18n/pupgui2_es.ts
i18n/pupgui2_fi.ts
i18n/pupgui2_fr.ts
i18n/pupgui2_it.ts
i18n/pupgui2_nb_NO.ts
i18n/pupgui2_nl.ts
i18n/pupgui2_pl.ts
i18n/pupgui2_pt.ts
i18n/pupgui2_pt_BR.ts
i18n/pupgui2_ru.ts
i18n/pupgui2_sv.ts
i18n/pupgui2_tr.ts
i18n/pupgui2_uk.ts
i18n/pupgui2_zh_TW.ts
pupgui2/constants.py
pupgui2/pupgui2.py

https://github.com/flathub/com.valvesoftware.Steam.CompatibilityTool.Proton-GE was marked as archived on January 8th and EOL on Flathub. This PR removes the mention of being able to download it from there.

pupgui2: remove references to compat tools on Flathub

---

pupgui2/pupgui2shortcutdialog.py
pupgui2/resources/ui/pupgui2_shortcutdialog.ui

This PR makes a few UIX tweaks to the Shortcut Editor dialog:
- Increase size of Shortcut Editor dialog to match Games List, both show games and it makes sense to give them an equal size imo
- Increase width of App Name column, open to discussion on adjusting this and/or adjusting the widths of other columns to give the information more breathing room! On the other dialogs, the App Name is given the most sizing priority, which is why I gave it the biggest size here.
- Always put App Name LineEdit cursor at beginning, so the start of the game name is shown instead of the end.
- Select all text in LineEdit when initially focused with mouse, this allows quick editing and also moves the cursor to the end of the LineEdit, such as when clicking on the game name, allowing a quick way to see the …

Shortcut Editor: Various UIX Tweaks

---

pupgui2/resources/ctmods/ctmod_boxtron.py

Fixes a typo found in https://github.com/DavidoTek/ProtonUp-Qt/issues/27#issuecomment-1910343839.
[This was my doing](https://github.com/DavidoTek/ProtonUp-Qt/pull/311/files#diff-3ea3745ae52687773ab601bf354442a59c64c0d248b2097be254e664dc28d0afR24) :sweat: I'll learn to spell properly one of these days, I promise! Even though I spelt it wrong *again* when writing the commit message...

Boxtron: Fix typo 'doxbox' -> 'dosbox'

---

pupgui2/pupgui2gamelistdialog.py

Fixing the problem when opening the game list, that contains a game with status denied.

FIX: awacy_icon denied problem

---

pupgui2/resources/ctmods/ctmod_winetkg_valve_otherdistro.py
pupgui2/resources/ctmods/ctmod_winetkg_winemaster.py

This PR changes the description of the Valve Wine and Vanilla Wine -tkg builds to note which branch they use for clarity.
- Valve Wine uses Valve's `bleeding_edge` branch, which is what their `experimental_X.X` branches are based on (ValveSoftware/wine branches: https://github.com/ValveSoftware/wine/branches). It also changes the name of the Vanilla Wine ctmod file for consistency with this change.
- The wine-tkg-git workflow calls this `wine-valvexbe` where "xbe" is e**X**perimental **B**leeding **E**dge.
- Vanilla Wine uses Wine Master built on an Ubuntu CI
- Verified the branch used with this line in `customisation.cfg`: https://github.com/Frogging-Family/wine-tkg-git/blob/edf80e3ecdcf69555f2359433003dd635b3b5798/wine-tkg-git/customization.cfg#L55
- Verified that this is not changed in …

Wine-tkg: Clarify Wine version used for Wine-tkg variants

---

pupgui2/pupgui2shortcutdialog.py

When using the Shortcut Editor (which is my new favourite thing :smile:) I instinctively pressed "Ctrl+F" to focus the search bar. I figured it would be a useful bit of functionality, so I decided to add it!
While adding it, I also thought a save shortcut would be handy, so I added that too.
There is some precedent for keyboard shortcuts in ProtonUp-Qt, as we already have some on the Main Menu, so I think it's okay to add them to the Shortcut Editor too :slightly_smiling_face: 
These shortcuts are bound using  `QKeySequence.Find` and `QKeySequence.Save`, which are Qt's built-in per-platform "constants" (I guess?) for these actions. Since we're only targetting Linux with ProtonUp-Qt, it isn't a huge deal, but I think it's nicer to be explicit with a shortcut key combination called "Save" …

Shortcut Editor: Add 'Find' and 'Save' keyboard shortcuts

---

pupgui2/lutrisutil.py
pupgui2/pupgui2ctinfodialog.py
pupgui2/pupgui2gamelistdialog.py

Some readability improvements that may help extending these checks later for future work, hopefully not too premature! :smile: 
When I was digging into #363 I noticed that some of the conditional logic was a bit long and seemingly arbitrary. To help with readability I made some generic utility functions that should explain better than the checks we were doing before.
For #363 we may need to extend the conditional logic i.e. in `pupgui2ctinfodialog.py`, we may need to add a check for whether a given runtime is in use. This would get pretty long, but with this format, we could make `is_lutris_game_using_runtime('dxvk', game.dxvk_version)` (or something along these lines, idk how we would want to do this just yet, and not too important for this PR :-) ).
The first function added is to check …

Lutris: Add some util functions for conditional game list parsing

---

pupgui2/constants.py
pupgui2/steamutil.py
pupgui2/util.py

Should fix #353.
All mentions to just "Steam" in this issue refer to Steam installed i.e. via package manager, not Steam Flatpak or Steam Snap :-) The problem could still apply to them I think, but I don't have them on-hand to test.
This PR changes the check in `util#available_install_directories` to be a bit stricter when checking for Steam installs. It now makes sure that the configuration files we need exist before marking a Steam installation as valid.
The core of the problem is that we can mark an invalid Steam installation as available because we only check if the directories that we need exist, not if the actual files we need exist. We need `libraryfolders.vdf` and `config.vdf` to perform various actions, but in `util#available_install_directories`, we only check `os.path.exists`. …

util: Check if Steam configuration files exist before marking as available

---

pupgui2/pupgui2customiddialog.py

Fix #370.
Almost forewent my usual PR format, but that would be no fun, right? :wink: 
Changes the check in the Custom Install Dialog that selects the default launcher to use an inline `if`, which fixes a crash if `self.launcher` is not a key in `self.install_locations_dict`. This currently occurs when there are no available launchers installed. We get a `KeyError` if no launchers are found, because `self.launcher` is not a valid key in `self.install_locations_dict`.
Apparently, in Python, `dictionary[key] or 'value'` will result in a `KeyError` if `key` is not defined. However in other cases, this does not happen. For example with an inline `if` I guess the conditional gets parsed first, like a "full" `if`, so you can do `dictionary[key] if key in dictionary else 'value'` safely, as …

Custom Install Directory: Use Inline `if` for Safer Default Launcher Selection

---

pupgui2/constants.py
pupgui2/resources/ctmods/ctmod_00winege.py
pupgui2/resources/ctmods/ctmod_kron4ekvanilla.py
pupgui2/resources/ctmods/ctmod_lutriswine.py
pupgui2/resources/ctmods/ctmod_winetkg_valve_otherdistro.py
pupgui2/resources/ctmods/ctmod_winetkg_winemaster.py

Close https://github.com/DavidoTek/ProtonUp-Qt/issues/373
---
@DavidoTek Requires additional filesystem permissions for the Flatpak, https://github.com/flathub/net.davidotek.pupgui2/
- `--filesystem=~/.local/share/winezgui/Runners/`
- `--filesystem=~/.var/app/io.github.fastrizwaan.WineZGUI/data/winezgui/Runners/`

Add winezgui support

---

AppImageBuilder.yml

Fix https://github.com/DavidoTek/ProtonUp-Qt/issues/378
- Include `libxcb-cursor0` in the AppImage
- Use the correct paths for cleaning unused Qt files (Debian's pip seems to change `/usr` to `/usr/local`, see https://github.com/DavidoTek/ProtonUp-Qt/issues/378#issuecomment-2071492202)

AppImage improvements (libxcb-cursor0, cleaning)

---

pupgui2/constants.py

Was tinkering around with the new Flatpak KDE 6.7 update to see if any of the small oddities were fixed (like the wrong cursor being used, and some things displaying incorrectly on Wayland, and they were fixed!) and happened to notice the copyright year wasn't bumped.
As far as I could see, this text isn't translated, and has only been changed a handful of times (most recently in #222). Making this text translatable _might_ be as straightforward as changing its usage in `pupgui2aboutdialog.py` to be `self.ui.lblAboutVersion.setText(self.tr(ABOUT_TEXT))`, but my understanding of translations is still not great. Since this text is using `.format` in `constants.py` and would not be calling it directly on `self.tr` I'm not sure if all that would play nicely together.

constants: Bump copyright year

---

pupgui2/pupgui2customiddialog.py

This PR adds functionality to open the Custom Install Dialog directory at the path in `self.ui.txtInstallDirectory` first, if it is a valid directory. If you enter some text manually, or select a folder using the dialog, and then open the dialog again, it will then open from that entered/selected path again, which can be handy if you only enter part of a path and want to browse for the rest, or if you select the wrong path and want to continue navigating from where you left off.
If the path is not valid, we fall back to `HOME_DIR`.
We already have a lambda that can check if an install directory is valid in `PupguiCustomInstallDirectoryDialog` called `is_valid_custom_install_path`, we use this to enable/disable the "Save" button each time the text in `txtInstallDirectory` is changed. So …

Custom Install Directory: Try to open txtInstallDirectory first

---

pupgui2/pupgui2customiddialog.py

This PR enables hidden folders by default for the Custom Install Directory dialog. This makes the dialog easier to browse when clicking through folders to find, for example, an alternative Steam installation location. Launcher installations are often in hidden directories, so I think it makes sense to enable hidden files by default.
This change also has the benefit of allowing suggestions when typing the path to a hidden folder. On `main`, if you type `~/.local/share/Steam`, you won't get any autocomplete, which might suggest a folder doesn't exist when it in fact does, the dialog is just hiding the hidden folder.
Since launchers often deal with hidden folders, I think it makes sense to have this on by default. For example if a user was using a custom version of a launcher that had a …

Custom Install Directory: Show hidden folders by default

---

AppImageBuilder.yml

Fix https://github.com/DavidoTek/ProtonUp-Qt/issues/390
Change `PYTHONPATH` from `${APPDIR}/usr/lib/python3.10/site-packages` to `${APPDIR}/usr/local/lib/python3.10/dist-packages`.
I need to check whether that really fixes it, marked as draft for now.

Change AppImage PYTHONPATH to local lib

---

pupgui2/pupgui2.py
pupgui2/pupgui2aboutdialog.py
pupgui2/resources/ui/pupgui2_aboutdialog.ui
pupgui2/resources/ui/pupgui2_ctbatchupdatedialog.ui
pupgui2/resources/ui/pupgui2_custominstalldirectorydialog.ui
pupgui2/resources/ui/pupgui2_installdialog.ui

Fix https://github.com/DavidoTek/ProtonUp-Qt/issues/360
Makes the dialogs resizable by adding a root layout and removing the "maximumSize" constraints.
---
Dialogs:

Make Dialogs resizable

---

pupgui2/constants.py

When using the Dark theme, the `ToolTipBase` colour was set to the same colour as the `ToolTipText` colour. Both were set to `Qt.white`. This meant the tooltip text would not be readable against the tooltip background.
This PR changes the `ToolTipBase` colour to match the Palette base colour (`12, 12, 12`), which is very close to pure black (`0, 0, 0`), making it contrast well against the tooltip text and making it readable. We could use either of these two, or `Qt.black`, but I opted to go with the window base colour. The difference is so minute my eyes cannot tell the difference :smile: 
<hr>
Here are also some comparisons with other options, `Qt.black` and `QColor(0, 0, 0)`:
<hr>
I caught this because I have switched to using the Dark theme. I put this down to Qt Wayland bugs with …

Theming: Use Base Palette Colour for Tooltip Background Instead of `Qt.white`

---

pupgui2/lutrisutil.py
pupgui2/pupgui2gamelistdialog.py

Fixes #397.
This PR fixes a crash in the Lutris Games List if some games have data as `None` that we expect to be defined.
I covered this a lot in #397 but to reiterate briefly: When loading the games list, we get our list of `LutrisGame`s with `lutrisutil#get_lutris_game_list`. We filter out Steam games from this list. Then we extract data from each `LutrisGame` and display it on the UI; the name, runner, install directory, and installation time, as well as some other data for tooltips.
However some games can be missing this information. Lutris stores information about its games in an sqlite3 database, `pga.db`, which we query. Some games in this DB may be missing a lot of information though. The example I encountered this with was by syncing my Lutris Steam list. It stored information …

Games List: Add checks for skipping invalid games

---

pupgui2/pupgui2.py
pupgui2/pupgui2aboutdialog.py

Replaces usage of `net.davidotek.pupgui2` around the codebase with `APP_ID`, which should always be equivalent. I noticed this when working on something unrelated and thought it would be a useful change for consistency :-) Didn't seem to break anything in my testing.

Main: Use `APP_ID` constant in place of `net.davidotek.pupgui2`

---

pupgui2/constants.py
pupgui2/dbusutil.py
pupgui2/pupgui2.py

This PR enables displaying Download Progress and Active Downloads count on Task Managers, Docks, etc that listen for the `com.canonical.Unity.LauncherEntry.Update` DBus signal. When downloading tools, a progress bar will now appear on the Task Manager / Dock, displaying the same progress as the progress bar on the main window, as well as a count of the total active downloads. This can be useful if you have many windows open across different screens, or conversely on a single small display like the Steam Deck where you may set a tool to download and then open another fullscreen window as screen real estate is at a premium. It provides a visual indication of download progress outside of the ProtonUp-Qt main window and download count, similar to what a browser might show when downloading …

pupgui2: Send Download Progress and Active Downloads to DBus

---

pupgui2/ctloader.py

I've been using basedPyright as my linter and it actually warned me that the `List` and `Tuple` types from `typing` are deprecated in Python 3.9. I knew newer Python versions supported using the syntax of `foo: list` but I didn't realise it was deprecated.
I was going to open a discussion asking what our stance is on typing and I think I will do after this, however this was a very straightforward drop-in replacement for these types. Further changes and perhaps further explicit typing changes can be made in future, but I will open a discussion around this before going any further :smile:

CtLoader: Remove deprecated types

---

pupgui2/constants.py
pupgui2/pupgui2.py
pupgui2/pupgui2gamelistdialog.py
pupgui2/resources/ctmods/ctmod_kron4ekvanilla.py
pupgui2/resources/ctmods/ctmod_steamtinkerlaunch.py
pupgui2/steamutil.py
pupgui2/util.py

We use a lot of `os.path.exists('/.flatpak-info')` calls to determine if we're running inside Flatpak. This can be stored as a constant. Maybe you could consider this a micro-optimisation as we don't call `os.path.exists` as much anymore, but my main motivation here was readibility.
I didn't test this in Flatpak, please feel free to do so to make sure I didn't screw anything up (or direct me on how to do it :smile:)
Thanks!
<hr>
P.S. - This touches the dreaded SteamTinkerLaunch ctmod :wink: I have a laptop again (that I installed SteamTinkerLaunch on using ProtonUp-Qt!) so I am planning to tinker around with that ctmod again and make the code a bit less scary.

constants: Use constant to determine if Flatpak

---

pupgui2/util.py

When troubleshooting to see if another issue was related to offline behaviour, I found out that if we open ProtonUp-Qt while offline, there is an ugly error coming from requests if we try to download the game list while offline.
This PR returns early from `download_awacy_gamelist` if we are offline. We do this before we even create the thread that tries to download the game list, which should be very, very slightly more efficient than doing this after the thread is created :sweat_smile:
<hr>
This has the side-effect of not creating the file at all if we open ProtonUp-Qt while offline. We use this file in `update_steamapp_awacystatus` to populate `SteamApp` anti-cheat info and we have a check that if the file doesn't exist, we return early. So no worries here.
Something to consider for the …

util: Don't download AWACY list if offline

---

README.md
pupgui2/steamutil.py
requirements.txt

Fix https://github.com/DavidoTek/ProtonUp-Qt/issues/415
Use `steam` and `vdf` dependency by  Solstice Game Studios:
- https://github.com/solsticegamestudios/vdf (`master` branch)
- https://github.com/solsticegamestudios/steam (`master` branch)

Use steam and vdf dependency by  Solstice Game Studios

---

.github/workflows/testing-ci.yml
tests/test_util.py

Fix https://github.com/DavidoTek/ProtonUp-Qt/issues/347
- Adds a CI workflow for Unit Testing using `pytest`
- Runs on *Pull Requests* and *Pushes to main*
- Currently tests on Ubuntu 22.04 and Python 3.10
- Adds an initial test for `util.py#get_random_game_name`
- Produces Markdown Test Report using [pytest-md](https://github.com/hackebrot/pytest-md)
---
<details>
<summary>Fixed Qt import for PyTest by installing libEGL and libxcbcommon and setting QT_QPA_PLATFORM=offscreen</summary>
**Previously**: Currently fails due to missing `libEGL`, i.e. the runner is headless but the Qt imports expect a graphics library. I will investigate that.
```sql
==================================== ERRORS ====================================
_____________________ ERROR collecting tests/test_util.py …
```

Add Unit Testing Workflow using PyTest

---

AppImageBuilder.yml
pupgui2/constants.py
setup.cfg
share/metainfo/net.davidotek.pupgui2.appdata.xml

Now with a two-digit minor :tada:
---
```
$ appstreamcli validate net.davidotek.pupgui2.appdata.xml
✔ Validation was successful: pedantic: 3
```

Bump version to 2.10.0

---

pupgui2/pupgui2customiddialog.py

WineZGUI was missing from the Custom Install Dialog dropdown. Sorry that I didn't find this in time for v2.10.0 (v.2.10.2?)'s release :sweat_smile:

CID: Add WineZGUI

---

pupgui2/pupgui2customiddialog.py
pupgui2/util.py

For #432 I was in and around the code for the Custom Install Dialog and found a couple of spots where I could make some changes.
- Remove unnecessary `print`s
- Add type hints for a couple of potentially ambiguous scenarios (not sure if we want to go all the day with the hints here, just added it for places where it might not be immediately obvious, mainly the `os.path.expanduser` calls)
- Reworked `set_selected_launcher` to be less nested ("Flat is better than nested" :wink:)
- Refactor + Type Hint for `util#get_combobox_index_by_value` to be less nested`

CID: Remove prints, some small cleanup+type hints

---

pupgui2/util.py
tests/test_util.py

Improve type hints for the unit test `test_get_random_game_name`, which also leads to improving the type hints for the `util#get_random_game_name` function, which was incorrect (it was hinting for a single list which could have Steam Games, Lutris Games, and/or Heroic Games, instead of a list which would _only_ contain one of these types rather than any combination).
This also means we get rid of some deprecated types in `util.py`.
Adding hints to unit tests and the functions they are testing is a good pairing imo; we are improving the hints of the actual function, and being explicit about the types we are expecting in our tests.

test_util: Improve type hints for `test_get_random_game_name`

---

pupgui2/datastructures.py
pupgui2/util.py
pyproject.toml
tests/test_util.py

This PR adds a unit test for `get_launcher_from_installdir`. It pulls the known `'install_dir'` for each launcher type from `POSSIBLE_INSTALL_LOCATIONS` from `constants.py` using a list comprehension. For Steam this might look like `[ '~/.local/share/Steam', '~/.snap/steam/root/compatibilitytools.d' ]`. We then create a list comprehension to store the result of `get_launcher_from_installdir`, and if the function works correctly we should get a list that contains the correct Launcher enum value. For Steam, this should look like `[ Launcher.STEAM, Launcher.STEAM ]` for example. Finally we assert that all of the values in the list containing the result of `get_launcher_from_installdir` for all the known `install_dir`s for that launcher, contain the expected Launcher enum type. For example …

test_util: Add test for `get_launcher_from_installdir`

---

pupgui2/steamutil.py

This PR casts our `a.game_name` assignment in `steamutil#update_steamapp_info` to always return a string. This fixes an error coming back `Error updating SteamApp info from appinfo.vdf: argument of type 'int' is not iterable` when `a.game_name` is not a string. With the new `appinfo.vdf` format, it seems name can be stored as an integer in `appinfo.vdf` now if the game's name in the library only contains numbers.
If we try to parse this game's name, it'll be stored as an integer, and we will run into the mentioned error when we try to perform string operations on it. The one causing the error mentioned is our [`elif 'Steamworks' in a.game_name`](https://github.com/DavidoTek/ProtonUp-Qt/blob/f2573d588a349fbdc77ccbe8fe720f41bf6a5305/pupgui2/steamutil.py#L310) check inside of the …

steamutil: Force SteamApp `game_name` to string

---

pupgui2/util.py
tests/test_util.py

Adds a test for the `get_dict_key_from_value`. It is written so it tests dicts with various different values, far more exotic than the couple of uses in the codebase that only test `dict[str, str]`. Although we do test that case we also test cases with more exotic key types, to allow the test to give us more confidence in this function.
I also updated the type hints in `get_dict_key_from_value` function itself, although they are mostly `Any` [and basedPyright does not like the `Any` type by default](https://github.com/detachhead/basedpyright/blob/main/docs/configuration.md#based-options). Although in this case I think it makes sense, dicts can have pretty much any key and value, so it makes sense that we could give this function a dict of `Any` and so the value we're searching for …

test_util: Add test for `get_dict_key_from_value`

---

pupgui2/dbusutil.py
pupgui2/pupgui2.py

This PR improves the type hinting in `dbusutil`.
- Fixes the default argument for `bus`. basedPyright was warning "Function calls and mutable objects not allowed within parameter default value expression", and when looking it up, [it seems this is for good reason](https://www.inspiredpython.com/article/watch-out-for-mutable-defaults-in-function-arguments). This has been replaced with defaulting the parameter to `None` and if it is `None`, assign it to `QDBusConnection.sessionBus` inside of the function body.
- This extra definition isn't typed because then it flags up a shadowed definition warning, even if the original hinting was possibly `None` and you just want to state in the re-definition that it will never be `None` (I guess the expectation is  that the code speaks for itself, and …

dbusutil: Type hinting improvements

---

pupgui2/networkutil.py
pupgui2/resources/ctmods/ctmod_luxtorpeda.py
pupgui2/resources/ctmods/ctmod_z0dxvk.py
pupgui2/util.py

This PR adds a new utility function, `download_file`, which takes the repeated download code in ctmods and turns it into a generic function.
This function lives in a new file, `networkutil.py`, and in future we can refactor and move the other network-related functions in here. Instead of further polluting `util.py` I figured I'd make a new file, which should also hopefully reduce the load when refactoring and moving the other methods for fetching from GitHub/GitLab into this file. Doing this should also aid in writing tests!
Each ctmod has to download the respective archive from its API. In almost every ctmods case (or *maybe actually for all of them*) the code is duplicated and does the same thing:
- Make a request to the API endpoint
- Figure out the filesize
- Figure out how many …

networkutil: Add new download_file utility function

---

pupgui2/heroicutil.py

This PR removes the deprecated type hints `List` and `Dict` imports from `typing` and replaces them with standard usage of `list` and `dict` that are available since Python 3.9. It also introduces some further type hints to other parts of the util file, although incomplete as typing some parts of this is a little complex given our reliance on parsing JSON (ideally we'll eventually have a JSON type alias, and we will more specifically hint in places where we know the structure of the JSON coming back, like if we know certain objects that we're performing `.get` on are always expected to be `dict[str, str]` for example). The rationale for further type hinting in the file is to make it easier for unit tests once we eventually get to that stage.

heroic_util: Remove deprecated type hints

---

pupgui2/pupgui2.py
pupgui2/util.py
tests/test_util.py

This PR creates a test for `build_headers_with_authorization`:
- Test that the token for GitHub gets pulled correctly.
- Test that the token for GitLab gets pulled correctly.
- Test that when we pass an unknown `token_type`, we don't set any authentication and handle it gracefully.
- Test that when we pass no tokens, we gracefully handle this and simply do not set any authentication.
- Test that the existing headers passed into the function are not overwritten by using a semi-realistic example of a `User-Agent` header.
I also added a docstring to the function and some type hinting.
When writing this test, I discovered a minor quirk that one could argue is a "defect": Python never passes copies, so when we perform operations on the current headers passed into the function, …

test_util: Add test for `build_headers_with_authorization`

---

pupgui2/pupgui2.py

Adds a tooltip to the installation location dropdown `comboInstallLocation` on the Main Menu which displays the dropdown's text. This can be useful if the path in the dropdown text is long, usually for paths. Resizing the window to see the full path is awkward, and not possible in some scenarios (like in GameScope). Some paths are so long that they are truncated in the dropdown itself at the Main Window's default size.
One thing not implemented here that might be cool to display is if the launcher path is custom. We could maybe add `[CUSTOM]` somewhere in the tooltip. But I think making it more obvious when a chosen launcher path is custom is a general enhancement for the future, so we could tackle it then.

pupgui2: Display install location combobox text in tooltip

---

pupgui2/datastructures.py
pupgui2/steamutil.py

Fix https://github.com/DavidoTek/ProtonUp-Qt/issues/424
Adds a new function `vdf_safe_load(vdf_file: str) -> dict` to `steamutil.py`
It opens and parses vdf files using the vdf library. Defective UTF-8 characters are replaced with a unicode question mark symbol. The error is printed in case of other Exceptions and an empty dict is returned.

Add vdf_safe_load function

---

pupgui2/pupgui2.py

Fixes #454.
This PR adds a check to `MainWindow#combo_install_location_current_index_changed` to ensure that `self.combo_install_location_index_map` is not empty. This `self.combo_install_location_index_map` could be empty if there are no launchers found by ProtonUp-Qt, and attempting to "Default" when no launchers are found results in the crash. This can be simulated by forcing `POSSIBLE_INSTALL_LOCATIONS = []` in `constants.py`.
If it is empty, then any attempt to index it will result in the error in #454, where we try to index this based on `self.ui.comboInstallLocation.currentIndex()`. This check avoids indexing when the list is empty, fixing the crash.
Whenever we press the "Default" button for Custom Install Directory, we attempt to update the `comboInstallLocations` dropdown so …

pupgui2: Don't attempt to map install_directory if `combo_install_location_index_map` is empty

---

pupgui2/pupgui2customiddialog.py

Based on suggestion in https://github.com/DavidoTek/ProtonUp-Qt/issues/454#issuecomment-2351673220.
This PR disables the "Default" button (`btnDefault`) if no Custom Install Directory has been configured. It also disables the button on click, if it successfully clears the value from the INI (i.e. if after clicking, the Custom Install Directory is successfully removed, toggle `btnDefault` enabled/disabled based on the `bool` cast of the value in the INI file).
The Custom Install Directory path is saved to the ProtonUp-Qt config file, and we can retrieve it using `config_custom_install_location`. I believe this is also responsible for writing out the path as well to the INI file. We can toggle whether `btnDefault` is enable on dialog load based on if `custom_install_directory` is defined. …

CID: Disable `btnDefault` if no Custom Install Directory path is set

---

pupgui2/pupgui2customiddialog.py

Fixes an issue I found when investigating another issue relating to the Custom Install Directory dialog.
This PR connects `txtInstallDirectory.textChanged` sooner, so that it can get triggered when we call `txtInstallDirectory.setText`. `textChanged` does validate text that is set programmatically, but won't do anything for our case if we connect it after we already set the text. This fixes an issue where when opening the Custom Install Directory dialog with a selected Custom Install Directory, the pre-populated path in the `txtInstallDirectory` Line Edit would not be seen as valid (because the `textChanged` signal to validate the path was not connected until after the text was set, so it did not know to validate the path on open of the dialog) and so the "Save" button would be kept as …

CID: Connect `txtInstallDirectory.textChanged` sooner

---

pupgui2/steamutil.py

Print the error message and return `{}` instead of raising a `KeyError` in `get_steam_vdf_compat_tool_mapping`.
If the `Value`/`value` key does not exist for some reason, ProtonUp-Qt will crash on start.
Returning `{}` prevents the crash and the functions calling `get_steam_vdf_compat_tool_mapping` should handle that case (although they might not work as expected).
(Update to `get_steam_vdf_compat_tool_mapping` which was introduced in https://github.com/DavidoTek/ProtonUp-Qt/pull/227)
---
Also, indicate which function prints the error message if the text is the same otherwise.

Steamutil: Do not raise error in get_steam_vdf_compat_tool_mapping

---

pupgui2/steamutil.py

Close https://github.com/DavidoTek/ProtonUp-Qt/issues/481
Ensures that `steamutil.py#vdf_safe_load(vdf_file)` always returns a dict, even when `vdf.loads` returns `None` or an error occurs while calling `vdf.loads`.
The PR does not allow ProtonUp-Qt work with a broken config as it is the case in #481, but prevents a crash while loading a broken config.

Make vdf_safe_load always return a dict

---

pupgui2/constants.py
pupgui2/resources/ctmods/ctmod_protoncachyos.py

Based on the ctmod for ProtonGE, it add support for Proton-CachyOS as discussed in #472.
The different architectures are currently shown as different releases in the selection list. `x86_64_v3` downloads will only be shown if the host CPU supports the required instruction sets.

Add ctmod for Proton-CachyOS

---

pupgui2/pupgui2.py
pupgui2/pupgui2installdialog.py

Adds a padding of 3px to the installed compat tool list in the main window and the installation dialog to help with mouse navigation.

Add a 3px padding to the main list and combobox items

---

pupgui2/networkutil.py

This PR fixes a bug in `networkutil#download_file` where our calculation for `current_chunk` could return `0`. Instead of `int`, we use `math.ceil` to make sure fractional results are rounded up.
An alternative solution could be to append `or 1` so that if the value is `0`, it is treated as Falsey and we default to `1`, but I think using `math.ceil` is a bit more elegant even if it means the extra import :-) But happy if we want to avoid the import to just use `int(...) or 1`.
I have tested with Luxtorpeda (Steam) and DXVK (Lutris), and this should not cause any regressions.
<hr>
This bug was discovered while I was working on porting `download_file` to Steam-Play-None, where the `current_chunk` calculation was returning `0` and causing a Division by Zero error. I have also confirmed that …

networkutil: Round up chunk_count to ensure it cannot be

---

pupgui2/resources/ctmods/ctmod_steamplaynone.py

This PR fixes installing Steam-Play-None over the top of an existing installation. Currently if we attempt to do this, installation will fail, and there will be an extracted `Steam-Play-None-main` folder in the `compatibilitytools.d` directory from the successful download and extraction but failed renaming of the folder.
[Screencast_20250302_193713.webm](https://github.com/user-attachments/assets/de5d8c78-2b5b-4d1e-a8bc-277ac8777936)
When we download Steam-Play-None, we download and extract the tar which comes out as `Steam-Play-None-main`. After successful extraction, we rename this folder to `Steam-Play-None`.
Trying to download Steam-Play-None again if a folder with the name `Steam-Play-None` already exists in the `compatibilitytools.d` directory (i.e. from an existing installation), …

Steam-Play-None: Fix extraction if tool already installed

---

pupgui2/resources/ctmods/ctmod_00protonge.py
pupgui2/resources/ctmods/ctmod_protoncachyos.py

This PR moves the download logic of GE-Proton to use `download_file` from `network_util`. Like #490, the primary benefit here is consistency, but this also allows us to simpify the recently merged Proton-CachyOS support #486. It was brought up in that PR that GE-Proton doesn't use this function, and now it does :-)
In my tests, GE-Proton downloads correctly still. If there are any concerns with the approach taken, let me know :-) 
Thanks!

GE-Proton: Use `download_file` from `network_util`

---

pupgui2/resources/ctmods/ctmod_protoncachyos.py

This PR removes the deprecated type hints from the `typing` module. They exist sprinkled throughout the codebase, and should be removed, so I don't mean to single out this ctmod. I spotted this as I'm eyeing some changes to help it further inherit from the GE-Proton ctmod in the future, so I was in and around here and noticed it. I have also removed a couple of unused imports from this Ctmod.
I also added the `@override` annotation to methods we override from GE-Proton, which we currently don't do elsewhere in the codebase, although it is something I also did in #498. Like with removing the old deprecated type hints, I hope to go through and add these around the codebase where relevant (I think only the Ctmods, maybe there's a Qt component we subclass for the Shortcut Editor but I'm not …

Proton-CachyOS: Remove deprecated Type Hinting

---

pupgui2/datastructures.py

Fixes #495.
This PR addresses two issues with how we currently fetch game config files for Lutris, which is used to display the CtInfo dialog and Games List dialog.
I tested this change on my laptop (uses the newer `~/.local/share/lutris/games` path), and this PR fixes the crash in #495 and finds the game config for the one game I have installed (GE-Proton9-25 for Battlenet displays properly in the Games List and CtInfo dialog). I have also tested this setup on my Desktop PC (uses the older `~/.config/lutris/games` path), which works correctly and displays the same games with and without this change.
Currently, we check for games in the `~/.config/lutris/games` folder and that folder only. However, we assume that if we get a Lutris config folder back at all from …

Lutris: Allow checking data directory for game configs

---

pupgui2/ctloader.py
pupgui2/pupgui2.py
tests/test_ctmods.py

Adds a test for loading ctmods using the CtLoader as ctmods are currently not tested in CI/CD:
- Check if all ctmods are loaded successfully
- Check if the advanced mode filter works
- Fix CtLoader: Return correct ctmod list if `launcher=None` and `advanced_mode=False`
- Fix CtLoader: `load_ctmods` will return `False` if not all ctmods were loaded successfully
The current tests do not verify that the ctmods are working, only whether they can be loaded successfully. This is especially interesting for testing for syntax errors and compatibility with the Python version of the test/build system.
@DavidoTek TODO for future PR: Test the functionality of individual ctmods (fetching releases, downloading, installing, ...)

Test: CtLoader

---

AppImageBuilder.yml
pupgui2/constants.py
setup.cfg
share/metainfo/net.davidotek.pupgui2.appdata.xml

- Added the Proton-CachyOS compatibility tool
- Added a new theme for the Steam Deck
- Added a new dialog for configuring GitHub and GitLab API access tokens
- Removed Wine-GE in favour of GE-Proton and UMU for Lutris

Bump version to 2.12.0

---

pupgui2/datastructures.py

"Spring cleaning" as they say :smile:

datastructures: Remove deprecated `Dict` type hint

---

pupgui2/lutrisutil.py

I kept meaning to do this one, but not sure why I never got around to it :sweat_smile:
Figure it's best to do these file-by-file at best, and if any bigger files (like the utils) need this, function-by-function or something around as granular as that. :-)

lutrisutil: Remove deprecated `List` type hint

---

pupgui2/pupgui2ctinfodialog.py

I had to look up the replacement for the `Union` type hint just to be sure, and I think I got it right :-) 
Reference: https://www.blog.pythonlibrary.org/2021/09/11/python-3-10-simplifies-unions-in-type-annotations/

CtInfo: Remove deprecated `List` and `Dict` type hints

---

pupgui2/steamutil.py

Little bit more significant cleanup here than the others. I had initially thought we'd need to go a little bit slower on these files, but I was expecting hundreds of usages for some reason. It didn't go as bad as I thought though :-)
Quick smoke testing hasn't pointed out any errors here, and as always I did these changes by hand which I felt was especially important here to make sure I didn't mess anything up :smile:

steamutil: Remove deprecated `Dict`, `List`, and `Union` type hints

---

pupgui2/util.py

Similar to #513, I thought this would be a trickier one to do and we would have a ton of usages, but going slow and by hand, it wasn't so bad :-)
This should be all of the deprecated type hints I think. I did a Find in Files for `from typing import` and the remaining usages outside of these last few PRs are all valid imports of `Any` and `Callable`.

util: Remove deprecated `Dict`, `List`, `Union`, `Tuple`, `Optional` type hints

---

pupgui2/resources/ctmods/ctmod_rtspgeproton.py

Noticed this when I was poking my nose around this file :smile:

RTSP-GE-Proton: Fix typo in ctmod name

---

pupgui2/pupgui2ctbatchupdatedialog.py

Small PR to remove an unused import, and while I was in here I added a couple of type hints I want to call out a type hint added for `layout` which should make it clearer when reading which layout we're referring to, which is why I specifically singled it out.
We may want to expand this in future, but I just added a couple that are low hanging fruit. For example we may want to actually validate and handle cases where `pkgutil.get_data` returns `None` (would apply to many other files that use UI files). The remaining typing changes will really come down to what kind of standards we want to set for the codebase, which is why I held off for now. It can be done at a later date :-)

Batch Update: Remove Unused Import and add Type Hints

---

pupgui2/resources/ctmods/ctmod_00protonge.py
pupgui2/resources/ctmods/ctmod_kron4ekvanilla.py
pupgui2/resources/ctmods/ctmod_northstarproton.py

This PR moves the GE-Proton ctmod over to using the `fetch_project_releases` util function that other ctmods use. It also allows us to avoid unnecessarily overriding `fetch_releases` in ctmods that don't need to. This likely would have worked before (see RTSP-GE-Proton) but using relying on a generic util function is probably safer than custom logic specifically for GE-Proton's `fetch_releases`.
In my tests, there has been no difference between the releases displayed or any issues downloading releases following this change for GE-Proton, NorthStar Proton, or Kron4ek Wine.
We now have more commonality between ctmods and less repeated code. We were able to remove `fetch_releases` overrides for RTSP-GE-Proton and Kron4ek Vanilla Wine Builds.
Thanks!

GE-Proton: Use `fetch_project_releases` util function

---

pupgui2/resources/ctmods/ctmod_protontkg_ntsync.py

Close #516.
This PR implements a Ctmod for downloading Proton-tkg with the NTSYNC patches for Wine Master.
I have tested that this successfully downloads and extracts a Proton-tkg version that is the same size as a manually downloaded archive. I also tested that the workflow ID in the dropdown matches that of the same verified Proton-tkg (Wine Master NTSYNC) ctmod (https://github.com/Frogging-Family/wine-tkg-git/actions/runs/14285965734).
However, I don't have a Kernel with the NTSYNC patches yet. I believe this is only included in Kernel 6.14+, and I am also not sure how to verify if NTSYNC is being used. But I have taken steps to verify that the archive downloaded is sane and matches what would be downloaded manually.
Note: It takes an absolute _age_ to download these archives from …

Ctmod: Add Proton-tkg (Wine Master NTSYNC)

---

pupgui2/resources/ctmods/ctmod_z0dxvk.py
pupgui2/resources/ctmods/ctmod_z2dxvknightly.py

Fixes #500.
This PR refactors the DXVK Nightly Ctmod to inherit from the DXVK Ctmod, as there is quite a bit of shared logic between these Ctmods.
This PR also fixes #500 by refactoring the logic of how we fetch releases. Much of the complexity in this PR comes from fixing #500, not from the refactor itself. This complexity would have arisen regardless of the refactor.
In order for DXVK Nightly to inherit from the main DXVK Ctmod, a slight rework was needed to the main DXVK Ctmod.
- We needed to create a `__get_data` method in order to allow the DXVK Nightly child class to override this method.
- It needs to override the `data` that comes back, so that it returns the data from `__fetch_github_data` (which works with `__fetch_artifact_from_commit` to get the GitHub Actions workflow …

DXVK Nightly: Simplify by Inheriting from DXVK Ctmod

---

pupgui2/resources/ctmods/ctmod_lutriswine.py

Fix a double assign for `protondir` that was almost certainly a typo. This mistake was introduced in [#498](https://github.com/DavidoTek/ProtonUp-Qt/pull/498/files#diff-d916515cda1a70b93f552eded09980921d90ca650dadbb3ccc9160873ba732a5R79), I guess I didn't have enough coffee that day :wink:

Lutris-Wine: Fix double-assign for `protondir`

---

tests/test_util.py

This PR implements a test for the `is_gitlab_instance` utility function.
We test against each element in our `GITLAB_API` list constant using [PyTest's Parametrize feature](https://docs.pytest.org/en/7.1.x/example/parametrize.html). Currently we only have one entry in this list, but if we had more in future, this would allow us to check to make sure if we add one that it this function should always work with all items in that list. We also then check a failing test case with the GitHub API to ensure that the function returns `False` when we expect it to.
Thanks!

test_util: Implement test for `is_gitlab_instance`

---

pupgui2/util.py

Previously, `read_update_config_value("myoption", "")` would read the value from the config instead of writing an empty string to it.
This PR modifies `read_update_config_value` to only read from the config if `None` is provided as `value` but not with `""`.
This fixes that the GitHub/GitLab access token dialog cannot be used to delete an API key by removing the key from the text box.
```python
read_update_config_value("myoption", None)    # read from config at "myoption"
read_update_config_value("myoption", "test")  # write "test" to config at "myoption"
read_update_config_value("myoption", "")      # write "" to config at "myoption" ***
read_update_config_value("myoption", None)    # read from config at "myoption"
read_update_config_value("myoption", "test")  # write "test" to config at …
```

util: Allow config empty string

---

.github/workflows/testing-ci.yml
pupgui2/util.py
tests/requirements.txt
tests/test_util.py

This PR implements unit tests for the `is_online` util function. We test the "happy path" (a successful response where `is_online` returns `True` and the response we get matches a sane successful response) and the "error path" (`is_online` returns `False` when we catch a `requests.ConnectionError` or a `requests.Timeout` error, and the response matches an expected stubbed error response).
Initially, I had written these tests out using [`requests-mock`](https://github.com/jamielennox/requests-mock), but [it seems that library is unmaintained](https://github.com/jamielennox/requests-mock/issues/262). So I rewrote the tests to use the [Responses library](https://github.com/getsentry/responses) which is more actively maintained.
For convenience, I opted to use `pytest-responses` which is a …

test_util: Implement tests for `is_online`

---

pupgui2/pupgui2.py
pupgui2/resources/ctmods/ctmod_00protonge.py
pupgui2/resources/ctmods/ctmod_kron4ekvanilla.py
pupgui2/resources/ctmods/ctmod_lutriswine.py

See also: #527
This PR changes the extract directory for GE-Proton, extracting it into Lutris' `runners/proton` folder instead of into `runners/wine`. Lutris expects Proton-based compatibility tools that run with UMU to be installed into `runners/proton` (this path being relative to the Lutris install location, i.e. `~/.local/share/lutris/runners/proton`).
Note that this is **one** approach, and I will detail an alternative approach at the bottom of this PR.
I added a \`get_extract_dir\` method to the GE-Proton Ctmod to set the value of `install_dir` to the expected extract dir for the launcher. Since for every other launcher we want to trust `install_dir`, we can return that as the default value from `get_extract_dir`. However if we're using Lutris then we need to tell it to use the …

GE-Proton: Use correct extract path for Lutris

---

tests/test_util.py

This PR implements a test for `util#compat_tool_available`. We give it a Parametrized list of dummy compatibility tool dictionaries containing only a `name` key (as that's all we need to test against), the string name of the tool we want to ensure is in a dictionary in the list of compatibility tool dictionaries, and the expected value of whether or not that name should be found.
The three cases we test are: A name that should be found, a distinct name that should not be found, and a substring name that should not be found (ensures cases where `GE-Proton9-27` is in the list but `GE-Proton9-2` is not, that the substring `GE-Proton9-2` is not flagged).
Thanks!

test_util: Implement test for `compat_tool_available`

---

pupgui2/util.py
tests/test_util.py

Related: #528 
Uses PyTest Parametrize for the `get_random_game_name` function. Also adds some more test scenarios for ensuring we always get a `str` back, and to ensure we properly handle unknown objects and empty lists :-)

test_util: Parametrize `get_random_game_name`

---

pupgui2/resources/ctmods/ctmod_00protonge.py
pupgui2/resources/ctmods/ctmod_protoncachyos.py

This PR makes a small refactor to the Proton-CachyOS Ctmod which removes the need to override all of the `GEProtonInstaller#get_tool` ctmod. Instead, we can just override `__get_data`, which was implemented as part of #498 - Long after this ctmod was implemented, this was not missed when this ctmod was implemented, but it is something we can take advantage of now.
In order to fully take advantage of this we did need to add an `__init__` definition which sets `self.release_format`, since the GE-Proton ctmod uses this to know how to extract the tarfile. In future, we may want an `__extract` method similar to what we do for DXVK, but the current implementation is fine. Even if it were moved to an `__extract` method, it should be fine to keep the current implementation so that ctmods which …

Proton-CachyOS: Override `__get_data` instead of `get_tool`

---

pupgui2/resources/ctmods/ctmod_protonsarek.py
pupgui2/util.py

Implements #464.
~~**NOTE**: [Proton-Sarek has regular and `-async` releases](https://github.com/pythonlover02/Proton-Sarek/releases/tag/Proton-Sarek9-27) for each of its tags, similar to what [Lutris-Wine does with fshack builds](https://github.com/lutris/wine/releases/tag/lutris-wine-7.2).~~
~~This PR does **not** currently display these, and will be in draft until I can implement this. Right now it seems to default to downloading the "-async" builds, but ideally we'd want to display "-async" as a separate tag just like we do for Lutris-Wine fshack builds. A similar approach may be a possible drop-in but I will work on it :-)~~
Support for downloading async and non-async builds was added in 517cdc0. The above note has been fully addressed :slightly_smiling_face: 
This PR implements …

Ctmod: Add Proton-Sarek

---

tests/test_ctmods.py
tests/test_util.py

This PR implements a unit test for the `get_combobox_index_by_value` utility function.
I tested this test with and without the `QT_QPA_PLATFORM=offset` environment variable. It's worth noting that [we set this environment variable in CI](https://github.com/DavidoTek/ProtonUp-Qt/blob/0c418459dd0dc27d9b20fd3757371a54b2b0e3cf/.github/workflows/testing-ci.yml#L37).
When running multiple tests that use a `QApplication`, I was running into an error along the lines of `Please destroy the QApplication singleton before creating a new QApplication instance.` This would happen if a test created a `QApplication()` and then another test tried to do the same thing.
Trying to fix this took a bit of research. I stumbled across [this comment on a …

test_util: Implement test for `get_combobox_index_by_value`

---

pupgui2/resources/ctmods/ctmod_00protonge.py
pupgui2/util.py

This PR implements a long-standing TODO item of mine, which is to implement fetching checksum data on `fetch_project_release_data`. This allows ctmods that need can validate checksums (currently only GE-Proton and Proton-CachyOS) to migrate to using `fetch_project_release_data` without losing the `checksum` functionality.
The main benefit here is that we can continue to bring, and to reduce duplication in child classes.
As an aside, I did test with Proton-CachyOS and it can be refactored to use this method as well (we can use `checksum_suffix=f'{arch}.sha512sum' so that it gets the checksum for the correct release asset even), and it is compatible with the changes in #523. So this additional functionality in `fetch_project_release_data` should be flexible enough for general use, I didn't …

GE-Proton: Refactor to use `fetch_project_release_data`

---

tests/test_heroicutil.py

This PR iimplements a test for the `is_heroic_launcher` util function, the first test for our `heroicutil.py` utility file. :smile: 
The test runs `is_heroic_launcher` against all of the launchers in our `POSSIBLE_INSTALL_LOCATIONS` constant. We do this using [PyTest's Parametrize functionality](https://docs.pytest.org/en/7.1.x/example/parametrize.html). The benefit of this is that if this variable ever changes and we need to check for a new Heroic install location, or a new entry will incorrectly cause `is_heroic_launcher` to return `True`, then this test will fail and we will catch that error.
Thanks!

test_heroicutil: Implement test for `is_heroic_launcher`

---

tests/test_steamutil.py

This PR implements a test for the `calc_shortcut_app_id` utility function, the first unit test for our `steamutil.py` utility file!
To test this, we generate a Shortcut AppID based on a dict with a `name` and `exe`. We then compare the result of calling `calc_shortcut_app_id` with the expected Shortcut AppID for this `name` and `exe` combination. To find this out, I just copied the utility function and ran it locally to generate some AppIDs for test data.
Thanks!

test_steamutil: Implement test for `calc_shortcut_app_id`

---

pupgui2/constants.py

In Lutris' repo, this is what is referenced in their desktop file's `Icon` key, and the name of their icon.

Use Lutris' official app ID

---

pupgui2/resources/ctmods/ctmod_protontkg.py

This PR refactors the Proton-tkg ctmod to use the `download_file` util function. This is in a similar vein to other PRs that migrate compatibility tools to using 
I am eyeing up a larger refactor and cleanup of this ctmod (improved type hinting, reducing code duplication between it and DXVK Nightly following #509, extracting the archive extraction logic into an `__extract` method that each ctmod can implement instead of the Proton-tkg ctmod having to be aware of how to extract all of its child classes, maybe some other fun things in future too!) and this PR is the beginnings of that :-)
This PR is opened as a draft as it is largely untested, and I want to make sure it works against all the Proton-tkg ctmods. I tested briefly with the main Proton-tkg Ctmod and it appeared to work, but we …

Proton-tkg: Refactor to use `download_file`

---

tests/test_util.py

This PR adds two tests for `util#create_compatibilitytools_folder`.
The first test ensures that we can create the compatibility tools folder for every launcher in `POSSIBLE_INSTALL_LOCATIONS` by creating the launcher parent directory (i.e. the path for the launcher itself, such as `~/.local/share/Steam`) and then ensuring that the `create_compatibilitytools_folder` call will create the compatibility tools install directory (such as `~/.local/share/Steam/compatibilitytools.d`). We use `FakeFilesystem` for this from `pyfakefs` to create all the parent directroy launcher folders.
The second test is that we do not make any compatibility tool directory if the launcher directory does not exist. All we do for this one is call `create_compatibilitytools_folder` and make sure the folders still …

test_util: Add test for `create_compatibilitytools_folder`
